import "dotenv/config";
import crypto from "node:crypto";
import fs from "node:fs";
import fsp from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import ExcelJS from "exceljs";
import { db,transaction } from "./db.js";
import { migrate } from "./migrate.js";
import { normalizeAnnotationInput,validateAnnotation,toDbAnnotation } from "./validation.js";
import { ANNOTATION_DB_COLUMNS } from "./annotation-schema.js";
import { randomId } from "./auth.js";
import { parsePhotoFilename } from "./photo-filename.js";
import { readPhotoExifGps } from "./photo-exif.js";
import { isImportMarkedComplete,isBlankStoredAnnotation,hasImportAnnotationData,blankStoredAnnotationSql } from "./annotation-import.js";
import { removeNulCharacters,sanitizeNulDeep,sanitizeTextFields } from "./text-sanitize.js";

function parseArgs(argv){const out={};for(let i=2;i<argv.length;i++){const token=argv[i];if(!token.startsWith("--"))continue;const key=token.slice(2);if(["apply","replace-annotations"].includes(key))out[key]=true;else out[key]=argv[++i];}return out;}
const args=parseArgs(process.argv);if(!args.workbook&&!args.photos&&!args.gps&&!args.stopovers){console.error("Usage: npm run import -- [--workbook /imports/data.xlsx] [--photos /imports/photos] [--gps /imports/data.txt] [--stopovers /imports/stopovers.gpkg] [--report /reports/report.json] [--apply]");process.exit(2);}
const apply=!!args.apply,workbookPath=args.workbook?path.resolve(args.workbook):null,photosPath=args.photos?path.resolve(args.photos):null,gpsPath=args.gps?path.resolve(args.gps):null,stopoversPath=args.stopovers?path.resolve(args.stopovers):null,photoRoot=path.resolve(process.env.PHOTO_DIR||"/data/photos"),reportPath=path.resolve(args.report||`/reports/import-report-${new Date().toISOString().replace(/[:.]/g,"-")}.json`);
const shaBuffer=(buffer)=>crypto.createHash("sha256").update(buffer).digest("hex");
const shaFile=async(file)=>shaBuffer(await fsp.readFile(file));
const execFileAsync=promisify(execFile);
const numberOrNull=(value)=>value===null||value===undefined||value===""?null:(Number.isFinite(Number(value))?Number(value):null);
function dateOrNull(value){if(value===null||value===undefined||value==="")return null;if(value instanceof Date&&!Number.isNaN(value.getTime()))return value;const text=String(value).trim().replace(" ","T"),date=new Date(/Z$|[+-]\d\d:?\d\d$/.test(text)?text:`${text}Z`);return Number.isNaN(date.getTime())?null:date;}
const sourcePayload=(row)=>sanitizeTextFields(Object.fromEntries(Object.entries(row).filter(([k])=>!k.startsWith("__")).map(([k,v])=>[k,v instanceof Date?v.toISOString():v]))).value;

async function listRecursive(root){const out=[];async function walk(dir){for(const entry of await fsp.readdir(dir,{withFileTypes:true})){const file=path.join(dir,entry.name);if(entry.isDirectory())await walk(file);else if(entry.isFile())out.push(file);}}await walk(root);return out;}
function excelCellValue(value){if(value&&typeof value==="object"&&"result" in value)return value.result;if(value&&typeof value==="object"&&Array.isArray(value.richText))return value.richText.map((part)=>part.text??"").join("");if(value&&typeof value==="object"&&"text" in value)return value.text;return value;}
async function readWorkbook(file){
  const workbook=new ExcelJS.Workbook();await workbook.xlsx.readFile(file);const sheet=workbook.getWorksheet("photos");if(!sheet)throw new Error("Workbook does not contain the 'photos' sheet.");const headers=[],nulIssues=[];
  sheet.getRow(1).eachCell({includeEmpty:true},(cell,column)=>{const result=removeNulCharacters(String(excelCellValue(cell.value)??""));headers[column]=result.value.trim();if(result.removed)nulIssues.push({type:"nul_characters_removed",sourceRow:1,field:headers[column]||`column_${column}`,removed:result.removed});});
  const rows=[];for(let rowNo=2;rowNo<=sheet.rowCount;rowNo++){const source=sheet.getRow(rowNo),row={__sourceRow:rowNo};let hasValue=false;for(let column=1;column<headers.length;column++){const field=headers[column];if(!field)continue;const result=sanitizeNulDeep(excelCellValue(source.getCell(column).value));if(result.removed)nulIssues.push({type:"nul_characters_removed",sourceRow:rowNo,field,removed:result.removed});const value=result.value;if(value!==null&&value!==undefined&&value!=="")hasValue=true;row[field]=value??null;}if(hasValue)rows.push(row);}
  return{rows,nulIssues};
}
function parseTsv(line){const out=[];let value="",quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){value+='"';i++;}else quoted=!quoted;}else if(c==="\t"&&!quoted){out.push(value);value="";}else value+=c;}out.push(value);return out;}
async function readGps(file){if(!file)return[];const lines=(await fsp.readFile(file,"utf8")).replace(/^\uFEFF/,"").split(/\r?\n/).filter((line)=>line.trim());if(lines.length<2)throw new Error("GPS file is empty.");const headers=parseTsv(lines[0]).map((x)=>x.trim()),out=[];for(let i=1;i<lines.length;i++){let cells=parseTsv(lines[i]);if(cells.length===headers.length+1)cells=cells.slice(1);if(cells.length<headers.length)continue;const row=Object.fromEntries(headers.map((h,j)=>[h,cells[j]])),individualId=String(row.id||row.UUID||"").trim(),lon=numberOrNull(row.lon??row.Longitude??row.longitude),lat=numberOrNull(row.lat??row.Latitude??row.latitude);if(!individualId||lon===null||lat===null||Math.abs(lat)>90||Math.abs(lon)>180)continue;const observedAt=dateOrNull(row.DateTime??row.GPS_time??row.Collecting_time),sequenceNo=numberOrNull(row.time_agg)??i,sourceHash=shaBuffer(Buffer.from(`${individualId}|${observedAt?.toISOString()||""}|${lon}|${lat}|${sequenceNo}`));out.push({individualId,observedAt,sequenceNo,lon,lat,altitudeM:numberOrNull(row.Altitude_m??row.Altitude??row.altitude),pointType:String(row.Type||"").trim()||null,countN:numberOrNull(row.countN),sourceHash,raw:row});}out.sort((a,b)=>a.individualId.localeCompare(b.individualId)||(a.observedAt?.getTime()||Infinity)-(b.observedAt?.getTime()||Infinity));return out;}
async function readStopovers(file){if(!file)return[];let geojson;if(/\.geojson$|\.json$/i.test(file))geojson=JSON.parse(await fsp.readFile(file,"utf8"));else{const command=["-f","GeoJSON","/vsistdout/",file];if(args["stopover-layer"])command.push(args["stopover-layer"]);const {stdout}=await execFileAsync("ogr2ogr",command,{maxBuffer:128*1024*1024});geojson=JSON.parse(stdout);}const out=[];for(const feature of geojson.features||[]){if(!feature.geometry)continue;const properties=feature.properties||{},individualId=String(properties.id||properties.Bird||"").trim();if(!individualId)continue;const id=shaBuffer(Buffer.from(JSON.stringify({individualId,geometry:feature.geometry,properties})));out.push({id,individualId,geometry:feature.geometry,properties,timeStart:dateOrNull(properties.time_start),timeEnd:dateOrNull(properties.time_end)});}return out;}

async function photoIndex(root){if(!root)return{count:0,byName:new Map(),byKey:new Map(),files:[]};const files=(await listRecursive(root)).filter((file)=>/\.(jpe?g|png|webp)$/i.test(file)),byName=new Map(),byKey=new Map();for(const file of files){const name=path.basename(file),relative=path.relative(root,file),parts=relative.split(path.sep).filter(Boolean),bird=parsePhotoFilename(name).bird||(parts.length>1?parts.at(-2):null),key=bird?`${bird}\0${name}`:null;if(!byName.has(name))byName.set(name,[]);byName.get(name).push(file);if(key){if(!byKey.has(key))byKey.set(key,[]);byKey.get(key).push(file);}}return{count:files.length,byName,byKey,files};}
function rowsFromPhotoFolders(index,root,workbookRows){const existing=new Set(workbookRows.map((row)=>`${String(row.Bird||"").trim()}\0${String(row.FileName||"").trim()}`));const rows=[];for(const file of index.files){const relative=path.relative(root,file),parts=relative.split(path.sep).filter(Boolean),filename=path.basename(file),parsed=parsePhotoFilename(filename),bird=parsed.bird||(parts.length>1?parts.at(-2):null);if(!bird)continue;const key=`${bird}\0${filename}`;if(!/^[A-Za-z0-9._-]+$/.test(bird)||existing.has(key))continue;existing.add(key);rows.push({__sourceRow:null,Bird:bird,FileName:filename,FilePath:relative,Date_time:parsed.captureTime,Analysed:"no"});}return rows;}
async function prepare(rows,index,report){
  const unique=new Map();for(const originalRow of rows){const row=sanitizeTextFields(originalRow,({field,removed})=>report.issues.push({type:"nul_characters_removed",sourceRow:originalRow.__sourceRow??null,field,removed})).value,filename=String(row.FileName||"").trim(),filenameMetadata=parsePhotoFilename(filename),bird=String(row.Bird||filenameMetadata.bird||"").trim();if(!bird||!filename||!/^[A-Za-z0-9._-]+$/.test(bird)||/[\\/]/.test(filename)||filename==="."||filename===".."){report.issues.push({type:"missing_or_invalid_identifier",sourceRow:row.__sourceRow});continue;}row.Bird=bird;const key=`${bird}\0${filename}`;if(unique.has(key)){report.issues.push({type:"duplicate_workbook_row",sourceRow:row.__sourceRow,firstSourceRow:unique.get(key).__sourceRow,sourceKey:key});continue;}unique.set(key,row);}
  const out=[];let checked=0;for(const row of unique.values()){
    const bird=String(row.Bird).trim(),filename=String(row.FileName).trim(),key=`${bird}\0${filename}`,keyMatches=index.byKey.get(key)||[],matches=keyMatches.length?keyMatches:(index.byName.get(filename)||[]);if(matches.length>1)report.issues.push({type:"duplicate_media_filename",sourceRow:row.__sourceRow,sourceKey:key,paths:matches});if(!matches.length&&photosPath)report.issues.push({type:"missing_media",sourceRow:row.__sourceRow,sourceKey:key});
    const sourceFile=matches[0]||null,captureTime=dateOrNull(row.Date_time)??parsePhotoFilename(filename).captureTime,elevationM=numberOrNull(row.Elevation_m);let sizeBytes=null,sha256=null,mimeType=null,exif={hasGps:false,latitude:null,longitude:null,altitudeM:null,gpsTime:null};
    if(sourceFile){const stat=await fsp.stat(sourceFile);sizeBytes=stat.size;sha256=await shaFile(sourceFile);mimeType=/\.png$/i.test(sourceFile)?"image/png":/\.webp$/i.test(sourceFile)?"image/webp":"image/jpeg";try{exif=await readPhotoExifGps(sourceFile);}catch(error){report.issues.push({type:"exif_read_error",sourceRow:row.__sourceRow,sourceKey:key,error:String(error.message||error)});}if(!exif.hasGps)report.issues.push({type:"missing_photo_geotag",sourceRow:row.__sourceRow,sourceKey:key});if(++checked%250===0)console.log(`Checked ${checked} photo files and EXIF geotags...`);}
    const altitudeM=exif.altitudeM,sourceStatus=isImportMarkedComplete(row.Analysed)?"complete":"unstarted",annotationValues=sanitizeTextFields(normalizeAnnotationInput(row,{altitude_m:altitudeM,elevation_m:elevationM}),({field,removed})=>report.issues.push({type:"nul_characters_removed",sourceRow:row.__sourceRow??null,field,removed})).value,validationErrors=validateAnnotation(annotationValues,sourceStatus);if(validationErrors.length)report.issues.push({type:"annotation_validation",sourceRow:row.__sourceRow,sourceKey:filename,errors:validationErrors});out.push({row,bird,filename,sourceFile,sizeBytes,sha256,mimeType,captureTime,latitude:exif.latitude,longitude:exif.longitude,altitudeM,elevationM,gpsTime:exif.gpsTime,locationSource:sourceFile?(exif.hasGps?"exif":"missing"):null,exifCheckedAt:sourceFile?new Date():null,validationErrors});
  }
  return out;
}

async function insertGps(client,points){for(let start=0;start<points.length;start+=250){const batch=points.slice(start,start+250),params=[],tuples=batch.map((p)=>{const i=params.length;params.push(p.individualId,p.observedAt,p.sequenceNo,p.lon,p.lat,p.altitudeM,p.pointType,p.countN,p.sourceHash,JSON.stringify(p.raw));return`($${i+1},$${i+2},$${i+3},$${i+4},$${i+5},$${i+6},$${i+7},$${i+8},$${i+9},$${i+10}::jsonb)`;});await client.query(`INSERT INTO gps_points(individual_id,observed_at,sequence_no,longitude,latitude,altitude_m,point_type,count_n,source_hash,raw_payload) VALUES ${tuples.join(",")} ON CONFLICT(source_hash) WHERE source_hash IS NOT NULL DO NOTHING`,params);}}
async function existingImportStats(items,gps,stopovers){
  const photoRows=(await db.query(`SELECT p.id,p.individual_id,p.filename,p.sha256,(a.photo_id IS NOT NULL) has_annotation,a.status annotation_status,${ANNOTATION_DB_COLUMNS.map((column)=>`a.${column}`).join(",")} FROM photos p LEFT JOIN photo_annotations a ON a.photo_id=p.id`)).rows;
  const photosByKey=new Map(photoRows.map((row)=>[`${row.individual_id}\0${row.filename}`,row])),knownMedia=new Set(photoRows.map((row)=>row.sha256).filter(Boolean));
  const knownGps=new Set();for(let start=0;start<gps.length;start+=5000){const hashes=gps.slice(start,start+5000).map((point)=>point.sourceHash);if(hashes.length)for(const row of (await db.query("SELECT source_hash FROM gps_points WHERE source_hash=ANY($1::text[])",[hashes])).rows)knownGps.add(row.source_hash);}
  const stopoverIds=stopovers.map((item)=>item.id),knownStopovers=new Set();for(let start=0;start<stopoverIds.length;start+=5000){const ids=stopoverIds.slice(start,start+5000);if(ids.length)for(const row of (await db.query("SELECT id FROM stopovers WHERE id=ANY($1::text[])",[ids])).rows)knownStopovers.add(row.id);}const stopoverSignatures=new Set((await db.query("SELECT individual_id,time_start,time_end FROM stopovers")).rows.map((row)=>`${row.individual_id}\0${row.time_start?.toISOString()||""}\0${row.time_end?.toISOString()||""}`)),isExistingStopover=(item)=>knownStopovers.has(item.id)||stopoverSignatures.has(`${item.individualId}\0${item.timeStart?.toISOString()||""}\0${item.timeEnd?.toISOString()||""}`),existingStopoverCount=stopovers.filter(isExistingStopover).length;
  const existingPhotoRecords=items.filter((item)=>photosByKey.has(`${item.bird}\0${item.filename}`)).length,mediaItems=items.filter((item)=>item.sourceFile),existingMedia=mediaItems.filter((item)=>item.sha256&&knownMedia.has(item.sha256)).length;
  const matchedAnnotations=items.map((item)=>({item,row:photosByKey.get(`${item.bird}\0${item.filename}`)})).filter(({row})=>row?.has_annotation),blankAnnotationsToFill=matchedAnnotations.filter(({item,row})=>isBlankStoredAnnotation(row)&&hasImportAnnotationData(item.row)).length;
  return{photoRecords:items.length,newPhotoRecords:items.length-existingPhotoRecords,existingPhotoRecords,mediaFilesFound:mediaItems.length,newMedia:mediaItems.length-existingMedia,existingMedia,blankAnnotationsToFill,annotationsToPreserve:matchedAnnotations.filter(({row})=>!isBlankStoredAnnotation(row)).length,gpsPoints:gps.length,newGpsPoints:gps.length-knownGps.size,duplicateGpsPoints:knownGps.size,stopovers:stopovers.length,newStopovers:stopovers.length-existingStopoverCount,existingStopovers:existingStopoverCount};
}
async function applyImport(items,gps,stopovers,report,workbookHash){await migrate();await fsp.mkdir(photoRoot,{recursive:true});const batchId=args["batch-id"]||randomId(),sourceName=args["source-name"]||[workbookPath,photosPath,gpsPath,stopoversPath].filter(Boolean).map((item)=>path.basename(item)).join(", ")||"browser import";await transaction(async(client)=>{await client.query("INSERT INTO import_batches(id,source_name,source_sha256,status,summary,created_by) VALUES($1,$2,$3,'started',$4::jsonb,$5) ON CONFLICT(id) DO UPDATE SET status='started',summary=EXCLUDED.summary,finished_at=NULL",[batchId,sourceName,workbookHash,JSON.stringify({dryRun:false}),args["created-by"]||null]);await client.query("DELETE FROM import_issues WHERE batch_id=$1",[batchId]);for(const id of new Set([...items.map((i)=>i.bird),...gps.map((p)=>p.individualId),...stopovers.map((s)=>s.individualId)]))await client.query("INSERT INTO individuals(id) VALUES($1) ON CONFLICT(id) DO NOTHING",[id]);await insertGps(client,gps);
  for(let i=0;i<items.length;i++){
    const item=items[i],safeRow=sanitizeTextFields(item.row).value,existingPhoto=(await client.query("SELECT storage_path FROM photos WHERE individual_id=$1 AND filename=$2",[item.bird,item.filename])).rows[0];let storagePath=existingPhoto?.storage_path||null;
    if(item.sourceFile&&!storagePath){const dir=path.join(photoRoot,item.bird);await fsp.mkdir(dir,{recursive:true});let target=path.join(dir,item.filename);if(fs.existsSync(target)&&await shaFile(target)!==item.sha256){const parsed=path.parse(item.filename);target=path.join(dir,`${parsed.name}-${item.sha256.slice(0,12)}${parsed.ext}`);}if(!fs.existsSync(target))await fsp.copyFile(item.sourceFile,target);storagePath=path.relative(photoRoot,target);}
    const result=await client.query(`INSERT INTO photos(id,individual_id,filename,capture_time,storage_path,original_path,source_url,mime_type,size_bytes,sha256,media_status,address,country,close_city,geo_desc,latitude,longitude,gps_time,location_source,exif_checked_at,altitude_m,elevation_m,source_row,source_payload) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24::jsonb) ON CONFLICT(individual_id,filename) DO UPDATE SET capture_time=COALESCE(EXCLUDED.capture_time,photos.capture_time),storage_path=COALESCE(photos.storage_path,EXCLUDED.storage_path),original_path=COALESCE(photos.original_path,EXCLUDED.original_path),source_url=COALESCE(photos.source_url,EXCLUDED.source_url),mime_type=COALESCE(photos.mime_type,EXCLUDED.mime_type),size_bytes=COALESCE(photos.size_bytes,EXCLUDED.size_bytes),sha256=COALESCE(photos.sha256,EXCLUDED.sha256),media_status=CASE WHEN photos.storage_path IS NOT NULL THEN photos.media_status ELSE EXCLUDED.media_status END,address=COALESCE(EXCLUDED.address,photos.address),country=COALESCE(EXCLUDED.country,photos.country),close_city=COALESCE(EXCLUDED.close_city,photos.close_city),geo_desc=COALESCE(EXCLUDED.geo_desc,photos.geo_desc),latitude=CASE WHEN EXCLUDED.location_source IS NOT NULL THEN EXCLUDED.latitude ELSE photos.latitude END,longitude=CASE WHEN EXCLUDED.location_source IS NOT NULL THEN EXCLUDED.longitude ELSE photos.longitude END,gps_time=CASE WHEN EXCLUDED.location_source IS NOT NULL THEN EXCLUDED.gps_time ELSE photos.gps_time END,location_source=COALESCE(EXCLUDED.location_source,photos.location_source),exif_checked_at=COALESCE(EXCLUDED.exif_checked_at,photos.exif_checked_at),altitude_m=COALESCE(EXCLUDED.altitude_m,photos.altitude_m),elevation_m=COALESCE(EXCLUDED.elevation_m,photos.elevation_m),source_row=EXCLUDED.source_row,source_payload=EXCLUDED.source_payload,updated_at=now() RETURNING id,altitude_m,elevation_m`,[randomId(),item.bird,item.filename,item.captureTime,storagePath,item.sourceFile,safeRow.FilePath,item.mimeType,item.sizeBytes,item.sha256,item.sourceFile?"available":"missing",safeRow.Address,safeRow.Country,safeRow.Close_city,safeRow.Geo_desc,item.latitude,item.longitude,item.gpsTime,item.locationSource,item.exifCheckedAt,item.altitudeM,item.elevationM,safeRow.__sourceRow,JSON.stringify(sourcePayload(safeRow))]);
    const photo=result.rows[0],sourceComplete=isImportMarkedComplete(safeRow.Analysed),values=sanitizeTextFields(normalizeAnnotationInput(safeRow,photo)).value,status=sourceComplete?"complete":"unstarted",dbValues=sanitizeTextFields(toDbAnnotation(values)).value,columns=ANNOTATION_DB_COLUMNS,importUser=args["created-by"]||null,params=[photo.id,status,...columns.map((c)=>dbValues[c]),importUser,importUser,status==="complete"?new Date():null],names=["photo_id","status",...columns,"created_by","updated_by","completed_at"],update=`status=EXCLUDED.status,${columns.map((c)=>`${c}=EXCLUDED.${c}`).join(",")},updated_by=EXCLUDED.updated_by,completed_at=EXCLUDED.completed_at,version=photo_annotations.version+1,updated_at=now()`,conflict=args["replace-annotations"]?`DO UPDATE SET ${update}`:hasImportAnnotationData(safeRow)?`DO UPDATE SET ${update} WHERE ${blankStoredAnnotationSql()}`:"DO NOTHING";await client.query(`INSERT INTO photo_annotations(${names.join(",")}) VALUES(${params.map((_,j)=>`$${j+1}`).join(",")}) ON CONFLICT(photo_id) ${conflict}`,params);if((i+1)%250===0)console.log(`Imported ${i+1}/${items.length} records...`);
  }
  for(const s of stopovers){const existing=(await client.query("SELECT id FROM stopovers WHERE individual_id=$1 AND time_start IS NOT DISTINCT FROM $2 AND time_end IS NOT DISTINCT FROM $3 ORDER BY created_at LIMIT 1",[s.individualId,s.timeStart,s.timeEnd])).rows[0];if(existing)await client.query("UPDATE stopovers SET geometry_geojson=$1::jsonb,properties=$2::jsonb WHERE id=$3",[JSON.stringify(s.geometry),JSON.stringify(s.properties),existing.id]);else await client.query("INSERT INTO stopovers(id,individual_id,time_start,time_end,geometry_geojson,properties) VALUES($1,$2,$3,$4,$5::jsonb,$6::jsonb) ON CONFLICT(id) DO UPDATE SET time_start=EXCLUDED.time_start,time_end=EXCLUDED.time_end,geometry_geojson=EXCLUDED.geometry_geojson,properties=EXCLUDED.properties",[s.id,s.individualId,s.timeStart,s.timeEnd,JSON.stringify(s.geometry),JSON.stringify(s.properties)]);}for(const issue of report.issues)await client.query("INSERT INTO import_issues(batch_id,issue_type,source_row,source_key,details) VALUES($1,$2,$3,$4,$5::jsonb)",[batchId,issue.type,issue.sourceRow||null,issue.sourceKey||null,JSON.stringify(issue)]);await client.query("UPDATE import_batches SET status='completed',summary=$1::jsonb,finished_at=now() WHERE id=$2",[JSON.stringify(report.summary),batchId]);});return batchId;}

async function main(){
  const workbookHash=workbookPath?await shaFile(workbookPath):null,workbookData=workbookPath?await readWorkbook(workbookPath):{rows:[],nulIssues:[]},workbookRows=workbookData.rows,index=await photoIndex(photosPath),rows=[...workbookRows,...rowsFromPhotoFolders(index,photosPath,workbookRows)],gps=await readGps(gpsPath),stopovers=await readStopovers(stopoversPath),report={generatedAt:new Date().toISOString(),mode:apply?"apply":"dry-run",inputs:{workbook:workbookPath,workbookSha256:workbookHash,photos:photosPath,gps:gpsPath,stopovers:stopoversPath},summary:{},issues:[...workbookData.nulIssues]},items=await prepare(rows,index,report),usedFiles=new Set(items.map((item)=>item.sourceFile).filter(Boolean));
  if(photosPath)for(const file of index.files)if(!usedFiles.has(file))report.issues.push({type:"unreferenced_media",sourceKey:path.basename(file),paths:[file]});
  const existing=await existingImportStats(items,gps,stopovers);report.summary={...existing,workbookRows:workbookRows.length,uniquePhotoRecords:items.length,mediaFilesFound:index.count,recordsWithMedia:items.filter((item)=>item.sourceFile).length,photosWithExifGps:items.filter((item)=>item.sourceFile&&item.locationSource==="exif").length,photosWithoutExifGps:items.filter((item)=>item.sourceFile&&item.locationSource==="missing").length,photoCoordinatesFromTrack:0,missingMedia:items.filter((item)=>!item.sourceFile&&photosPath).length,gpsIndividuals:new Set(gps.map((point)=>point.individualId)).size,completeSourceRows:workbookRows.filter((row)=>isImportMarkedComplete(row.Analysed)).length,unfinishedSourceRows:workbookRows.filter((row)=>!isImportMarkedComplete(row.Analysed)).length,nulCharactersRemoved:report.issues.filter((issue)=>issue.type==="nul_characters_removed").reduce((total,issue)=>total+Number(issue.removed||1),0),issues:report.issues.length};
  if(apply)report.batchId=await applyImport(items,gps,stopovers,report,workbookHash);await fsp.mkdir(path.dirname(reportPath),{recursive:true});await fsp.writeFile(reportPath,JSON.stringify(report,null,2));console.log(JSON.stringify(report.summary,null,2));console.log(`${apply?"Import completed":"Dry run completed"}. Report: ${reportPath}`);
}
main().catch((error)=>{console.error(error);process.exitCode=1;}).finally(()=>db.end());
