import "dotenv/config";
import crypto from "node:crypto";
import fs from "node:fs";
import fsp from "node:fs/promises";
import path from "node:path";
import express from "express";
import cors from "cors";
import helmet from "helmet";
import rateLimit from "express-rate-limit";
import multer from "multer";
import nodemailer from "nodemailer";
import sharp from "sharp";
import { db, transaction } from "./db.js";
import { migrate } from "./migrate.js";
import {
  assertAuthConfiguration,normalizeEmail,publicUser,signToken,signMediaToken,authenticateUser,authenticateMediaUser,requireRole,
  canAccessIndividual,canAnnotateIndividual,accessSql,hashPassword,temporaryPassword,verifyPassword,audit,randomId
} from "./auth.js";
import { canEditAnnotation } from "./role-policy.js";
import { publicAnnotationSchema,ANNOTATION_FIELDS,ANNOTATION_DB_COLUMNS,EXTENSIBLE_ANNOTATION_FIELDS,normalizeReviewField } from "./annotation-schema.js";
import { normalizeAnnotationInput,validateAnnotation,toDbAnnotation,fromDbAnnotation } from "./validation.js";
import { queryExportRows,rowToExport,sendCsv,sendXlsx,sendGeoJson,sendKml,sendZip } from "./export.js";
import { stageBrowserImport,runStagedImport,removeStagedImport } from "./admin-import.js";
import { parsePhotoFilename } from "./photo-filename.js";
import { readPhotoExifGps } from "./photo-exif.js";
import { inspectTabularHeaders } from "./tabular-import.js";
import { backfillPhotoLocationsFromTrack,DEFAULT_PHOTO_GPS_MAX_OFFSET_MINUTES,nearestTrackPoint,shouldUpgradePhotoMedia } from "./photo-location.js";
import { sendOriginalPhoto,sendPreviewOrOriginal } from "./photo-response.js";
import { contributionForUser,ensurePhotoAccess,getContributionSettings,refreshContribution } from "./contribution-store.js";
import { advanceBrowseCycle } from "./browse-cycle.js";
import { normalizeContributionSettings } from "./contribution.js";

assertAuthConfiguration();
await migrate();

const app=express(), port=Number(process.env.PORT||3000);
const photoDir=path.resolve(process.env.PHOTO_DIR||"/data/photos"), previewDir=path.join(photoDir,"previews"), uploadDir=path.join(photoDir,".uploads"), importStageDir=path.join(photoDir,".import-staging"), importUploadDir=path.join(photoDir,".import-uploads");
const publicApiUrl=String(process.env.PUBLIC_API_URL||"").replace(/\/$/,"");
const publicAppUrl=String(process.env.PUBLIC_APP_URL||"").replace(/\/$/,"")+"/";
const photoGpsMaxOffsetMinutes=Math.max(1,Number(process.env.PHOTO_GPS_MAX_OFFSET_MINUTES)||DEFAULT_PHOTO_GPS_MAX_OFFSET_MINUTES);
await Promise.all([photoDir,previewDir,uploadDir,importStageDir,importUploadDir].map((dir)=>fsp.mkdir(dir,{recursive:true})));

async function repairMisclassifiedPhotoImports(){
  const mistakenIds=["stork-log-photos-main","stork-log-photos"],rows=(await db.query("SELECT id,individual_id,filename FROM photos WHERE individual_id=ANY($1::text[])",[mistakenIds])).rows,repairedIds=[];
  await transaction(async(client)=>{
    for(const row of rows){const parsed=parsePhotoFilename(row.filename);if(!parsed.bird||parsed.bird===row.individual_id)continue;await client.query("INSERT INTO individuals(id) VALUES($1) ON CONFLICT(id) DO NOTHING",[parsed.bird]);const result=await client.query("UPDATE photos SET individual_id=$1,capture_time=COALESCE(capture_time,$2),updated_at=now() WHERE id=$3 AND NOT EXISTS(SELECT 1 FROM photos target WHERE target.individual_id=$1 AND target.filename=$4) RETURNING id",[parsed.bird,parsed.captureTime,row.id,row.filename]);if(result.rows[0])repairedIds.push(result.rows[0].id);}
    for(const mistakenId of mistakenIds)await client.query("UPDATE individuals SET active=false,public_visible=false,updated_at=now() WHERE id=$1 AND NOT EXISTS(SELECT 1 FROM photos WHERE individual_id=$1)",[mistakenId]);if(repairedIds.length)await client.query("INSERT INTO audit_log(action,entity_type,payload) VALUES('misclassified_photo_import_repaired','photo_import',$1::jsonb)",[JSON.stringify({repaired:repairedIds.length,sourceIndividuals:mistakenIds})]);
  });
  if(repairedIds.length)console.log(`Repaired ${repairedIds.length} photo records imported under a folder name.`);
}
await repairMisclassifiedPhotoImports();
async function indexStoredPhotoExif(){
  const rows=(await db.query("SELECT id,storage_path FROM photos WHERE media_status='available' AND exif_checked_at IS NULL")).rows;if(!rows.length)return;let next=0,withGps=0,withoutGps=0;
  const worker=async()=>{while(next<rows.length){const row=rows[next++],file=safeStorage(row.storage_path);let exif={hasGps:false,latitude:null,longitude:null,altitudeM:null,gpsTime:null};if(file&&fs.existsSync(file))try{exif=await readPhotoExifGps(file);}catch(error){console.warn(`EXIF read failed for ${row.id}.`,error.message);}await db.query("UPDATE photos SET latitude=CASE WHEN $4='exif' THEN $1 ELSE latitude END,longitude=CASE WHEN $4='exif' THEN $2 ELSE longitude END,gps_time=CASE WHEN $4='exif' THEN $3 ELSE gps_time END,location_source=CASE WHEN $4='exif' THEN 'exif' ELSE COALESCE(location_source,'missing') END,exif_checked_at=now(),altitude_m=COALESCE($5,altitude_m),updated_at=now() WHERE id=$6",[exif.latitude,exif.longitude,exif.gpsTime,exif.hasGps?"exif":"missing",exif.altitudeM,row.id]);if(exif.hasGps)withGps++;else withoutGps++;}};
  await Promise.all(Array.from({length:Math.min(6,rows.length)},()=>worker()));await db.query("INSERT INTO audit_log(action,entity_type,payload) VALUES('photo_exif_indexed','photo_import',$1::jsonb)",[JSON.stringify({checked:rows.length,withGps,withoutGps,coordinatesFromTrack:0})]);console.log(`Indexed EXIF geotags: ${withGps} with GPS, ${withoutGps} without GPS.`);
}
await indexStoredPhotoExif();
const backfilledPhotoLocations=await backfillPhotoLocationsFromTrack(db,photoGpsMaxOffsetMinutes);
if(backfilledPhotoLocations)console.log(`Matched ${backfilledPhotoLocations} photos without EXIF GPS to the nearest track point.`);
await db.query("UPDATE import_batches SET status='failed',summary=summary||$1::jsonb,finished_at=now() WHERE status='started'",[JSON.stringify({error:"server_restarted_during_import"})]);

if(String(process.env.TRUST_PROXY||"")==="1")app.set("trust proxy",1);
app.use(helmet({crossOriginResourcePolicy:{policy:"cross-origin"}}));
app.use(cors({
  origin(origin,callback){const allowed=String(process.env.CORS_ORIGIN||"").split(",").map((x)=>x.trim()).filter(Boolean); if(!origin||allowed.includes(origin))return callback(null,true); callback(new Error("Origin is not allowed by CORS."));},
  exposedHeaders:["Content-Disposition","ETag"]
}));
app.use(express.json({limit:"3mb"})); app.use(express.urlencoded({extended:false}));
const loginLimiter=rateLimit({windowMs:15*60*1000,limit:12,standardHeaders:true,legacyHeaders:false});
const writeLimiter=rateLimit({windowMs:60*1000,limit:120,standardHeaders:true,legacyHeaders:false});
const uploadPhoto=multer({dest:uploadDir,limits:{fileSize:Math.max(1,Number(process.env.MAX_PHOTO_MB||30))*1024*1024},fileFilter:(_req,file,cb)=>cb(null,/^image\/(jpeg|png|webp)$/i.test(file.mimetype))});
const uploadImport=multer({dest:importUploadDir,limits:{fileSize:Math.max(1,Number(process.env.MAX_IMPORT_FILE_MB||4096))*1024*1024,files:6005,parts:6020}}).fields([{name:"workbook",maxCount:1},{name:"gps",maxCount:1},{name:"stopovers",maxCount:1},{name:"archive",maxCount:1},{name:"photos",maxCount:6000}]);
const uploadTableInspect=multer({dest:importUploadDir,limits:{fileSize:Math.max(1,Number(process.env.MAX_IMPORT_FILE_MB||4096))*1024*1024}}).single("workbook");

const positiveInt=(value,fallback,max)=>{const n=Number.parseInt(value,10);return Number.isFinite(n)&&n>0?Math.min(n,max):fallback;};
const iso=(value)=>{if(!value)return null;const date=value instanceof Date?value:new Date(value);return Number.isNaN(date.getTime())?null:date.toISOString();};
const imageUrl=(id,user,preview=false)=>user?`${publicApiUrl}/api/public/photos/${encodeURIComponent(id)}/image?media_token=${encodeURIComponent(signMediaToken(user,id))}${preview?"&kind=preview":""}`:null;
const mediaGrantSql=(photoAlias,userRef)=>`(EXISTS(SELECT 1 FROM user_browse_cycle_state cycle JOIN user_browse_cycle_photos unlocked ON unlocked.user_id=cycle.user_id AND unlocked.cycle_no=cycle.cycle_no WHERE cycle.user_id=${userRef} AND unlocked.photo_id=${photoAlias}.id) OR EXISTS(SELECT 1 FROM photo_annotations completed WHERE completed.photo_id=${photoAlias}.id AND completed.status='complete' AND completed.completed_by=${userRef}) OR EXISTS(SELECT 1 FROM restricted_annotation_focus focus WHERE focus.user_id=${userRef} AND focus.photo_id=${photoAlias}.id) OR EXISTS(SELECT 1 FROM annotation_tasks task WHERE task.assigned_to=${userRef} AND task.photo_id=${photoAlias}.id AND task.status='assigned'))`;
function photoPublic(row,user){return{id:row.id,bird:row.individual_id,filename:row.filename,captureTime:iso(row.capture_time),lat:row.latitude==null?null:Number(row.latitude),lon:row.longitude==null?null:Number(row.longitude),gpsTime:iso(row.gps_time),locationSource:row.location_source||null,altitudeM:row.altitude_m==null?null:Number(row.altitude_m),elevationM:row.elevation_m==null?null:Number(row.elevation_m),mediaGranted:!!row.media_granted,imageUrl:imageUrl(row.id,user),previewUrl:imageUrl(row.id,user,true)};}
function photoJoined(row,user){return{...photoPublic(row,user),address:row.address,country:row.country,closeCity:row.close_city,geoDescription:row.geo_desc,filePath:row.source_url||row.original_path||row.storage_path||null,mimeType:row.mime_type,sizeBytes:row.size_bytes==null?null:Number(row.size_bytes),sha256:row.sha256,mediaStatus:row.media_status,sourceRow:row.source_row,status:row.status||"unstarted",version:Number(row.version||0),annotation:fromDbAnnotation(row),photoCreatedAt:iso(row.photo_created_at||row.created_at),photoUpdatedAt:iso(row.photo_updated_at||row.updated_at),updatedAt:iso(row.annotation_updated_at),updatedBy:row.updated_by_name?{id:row.updated_by,name:row.updated_by_name}:null,canEdit:row.can_edit===undefined?null:!!row.can_edit,isMine:row.is_mine===undefined?null:!!row.is_mine};}
function safeStorage(storagePath){if(!storagePath)return null;const absolute=path.resolve(photoDir,storagePath),rel=path.relative(photoDir,absolute);return rel.startsWith("..")||path.isAbsolute(rel)?null:absolute;}
async function resolveUploadedPhotoLocation(individualId,captureTime,exif){
  if(exif.hasGps)return{latitude:exif.latitude,longitude:exif.longitude,gpsTime:exif.gpsTime||captureTime||null,altitudeM:exif.altitudeM,locationSource:"exif"};
  if(!captureTime)return{latitude:null,longitude:null,gpsTime:null,altitudeM:null,locationSource:"missing"};
  const padding=photoGpsMaxOffsetMinutes*60,result=await db.query(`SELECT observed_at,longitude,latitude,altitude_m FROM gps_points WHERE individual_id=$1 AND observed_at BETWEEN $2::timestamptz-($3::double precision*interval '1 second') AND $2::timestamptz+($3::double precision*interval '1 second') ORDER BY abs(extract(epoch FROM observed_at-$2::timestamptz)) LIMIT 2`,[individualId,captureTime,padding]),points=result.rows.map((row)=>({observedAt:row.observed_at,lon:Number(row.longitude),lat:Number(row.latitude),altitudeM:row.altitude_m==null?null:Number(row.altitude_m)})),fallback=nearestTrackPoint(points,captureTime,photoGpsMaxOffsetMinutes);
  return fallback?{latitude:fallback.lat,longitude:fallback.lon,gpsTime:fallback.observedAt,altitudeM:fallback.altitudeM,locationSource:"track"}:{latitude:null,longitude:null,gpsTime:null,altitudeM:null,locationSource:"missing"};
}

async function servePhoto(req,res,next,publicOnly=true){try{
  const result=await db.query(`SELECT id,storage_path,mime_type,sha256,public_visible,media_status FROM photos WHERE id=$1 ${publicOnly?"AND public_visible=true":""}`,[req.params.id]);
  const photo=result.rows[0]; if(!photo||photo.media_status!=="available")return res.status(404).json({error:"photo_not_found"});
  const original=safeStorage(photo.storage_path); if(!original||!fs.existsSync(original))return res.status(404).json({error:"photo_file_missing"});
  const stat=fs.statSync(original),etag=`\"${photo.sha256||`${photo.id}-${stat.size}`}\"`; if(req.headers["if-none-match"]===etag)return res.status(304).end();
  res.setHeader("ETag",etag);res.setHeader("Cache-Control","private, max-age=900, no-transform");
  if(req.query.kind!=="preview")return sendOriginalPhoto(res,next,{file:original,mimeType:photo.mime_type||"image/jpeg"});
  const preview=path.join(previewDir,`${photo.id}.webp`);
  return sendPreviewOrOriginal(res,next,{original,originalMimeType:photo.mime_type||"image/jpeg",preview,createPreview:(temporary)=>sharp(original).rotate().resize({width:720,height:720,fit:"inside",withoutEnlargement:true}).webp({quality:78}).toFile(temporary),onFallback:(error)=>console.warn(`Preview unavailable for ${photo.id}; serving original.`,error.message)});
}catch(error){next(error);}}

async function authorizeMediaAndServe(req,res,next){try{const access=await transaction((client)=>ensurePhotoAccess(client,req.user,req.params.id,{purpose:"browse"}));if(!access.allowed)return res.status(access.http||403).json({error:access.error,contribution:access.profile||null});return servePhoto(req,res,next,false);}catch(error){next(error);}}

async function assignments(userId,client=db){const result=await client.query("SELECT individual_id FROM user_individual_access WHERE user_id=$1 ORDER BY individual_id",[userId]);return result.rows.map((r)=>r.individual_id);}
async function annotationPermission(user,photo,current,client=db){const assigned=await canAnnotateIndividual(user,photo.individual_id,client),taskAssigned=!!(await client.query("SELECT 1 FROM annotation_tasks WHERE photo_id=$1 AND assigned_to=$2 AND status='assigned'",[photo.id,user.id])).rows[0];return canEditAnnotation({user,current,assigned,taskAssigned});}
async function setAssignments(client,userId,ids=[]){await client.query("DELETE FROM user_individual_access WHERE user_id=$1",[userId]);for(const id of new Set(ids)){await client.query("INSERT INTO user_individual_access(user_id,individual_id) SELECT $1,$2 WHERE EXISTS(SELECT 1 FROM individuals WHERE id=$2)",[userId,String(id)]);}}
function mailTransport(){return process.env.SMTP_HOST?nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:String(process.env.SMTP_SECURE||"false")==="true",auth:process.env.SMTP_USER?{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}:undefined}):null;}
function roleDescription(role){return{admin:{label:"Administrator",permissions:"może zarządzać użytkownikami, importować dane oraz przeglądać, edytować, eksportować i moderować wszystkie rekordy."},coordinator:{label:"Koordynator",permissions:"może przeglądać i edytować wszystkie rekordy, eksportować dane, obsługiwać weryfikację i moderować kategorie, ale nie zarządza użytkownikami ani importem."},annotator:{label:"Użytkownik",permissions:"może przeglądać wszystkie rekordy, edytować własne i rozpoczynać nieopisane rekordy przypisanych osobników, a także używać ocen, prywatnego sejfu zdjęć i zgłoszeń do weryfikacji."}}[role]||{label:role,permissions:"dostęp zgodny z ustawieniami konta."};}
function inviteMessage(user,password,profile=null){
  const subject="Zaproszenie do Stork Photo Editor",role=roleDescription(user.role),restricted=user.role==="annotator"&&!!user.restricted_contributor,settings=profile?.settings||{},allowance=settings.initialBrowsingAllowance??30,bestThreshold=settings.bestPicturesThreshold??50,fullThreshold=settings.fullAccessThreshold??400;
  const accessDescription=restricted?["Tryb konta: Restricted Contributor.","Zasady dostępu:",`- W każdym cyklu możesz odkryć maksymalnie ${allowance} nowych zwykłych zdjęć. Ponowne otwarcie zdjęcia z bieżącego cyklu nie zużywa kolejnego miejsca.`,`- Po wykorzystaniu puli wybierz Start annotating. Ukończenie jednego rekordu jako complete rozpoczyna nowy cykl z pulą ${allowance} zdjęć.`,"- Zdjęcia ukończone przez Ciebie pozostają zawsze dostępne i nie zużywają bieżącej puli.",`- Prywatny sejf zdjęć odblokuje się po ${bestThreshold} ukończonych adnotacjach.`,`- Pełny dostęp do kolekcji odblokuje się po ${fullThreshold} ukończonych adnotacjach.`,"- Limity są chronione przez serwer i obowiązują również przy filtrach, tabeli oraz bezpośrednich adresach zdjęć."]:[];
  const body=[`Witaj ${user.name},`,"","Masz konto w aplikacji Stork Photo Editor.","",`Aplikacja: ${publicAppUrl}`,`Email: ${user.email}`,`Twoja rola: ${role.label}.`,`Uprawnienia: ${restricted?"możesz opisywać przydzielone zdjęcia i stopniowo odblokowywać dostęp przez ukończone adnotacje.":role.permissions}`,...(accessDescription.length?["",...accessDescription]:[]),"",`Hasło tymczasowe: ${password}`,"","Po pierwszym logowaniu trzeba zmienić hasło.","","Instrukcja:","1. Otwórz aplikację.","2. Zaloguj się emailem i hasłem tymczasowym.","3. Ustaw własne hasło.","4. Rozpocznij pracę z przydzielonymi zdjęciami.","","Stork Photo Editor"].join("\n"),params=new URLSearchParams({view:"cm",fs:"1",to:user.email,su:subject,body});return{subject,body,gmailUrl:`https://mail.google.com/mail/?${params}`,mailtoUrl:`mailto:${encodeURIComponent(user.email)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`};
}
async function invite(user,password){const profile=user.role==="annotator"&&user.restricted_contributor?await contributionForUser(db,user):null,message=inviteMessage(user,password,profile),transport=mailTransport();if(!transport)return{sent:false,temporaryPassword:password,gmailUrl:message.gmailUrl,mailtoUrl:message.mailtoUrl,reason:"smtp_not_configured"};try{await transport.sendMail({from:process.env.MAIL_FROM||"Stork Photo Editor <noreply@example.com>",to:user.email,subject:message.subject,text:message.body});return{sent:true};}catch(error){console.error(`Invitation email failed for ${user.email}.`,error);return{sent:false,temporaryPassword:password,gmailUrl:message.gmailUrl,mailtoUrl:message.mailtoUrl,reason:"smtp_send_failed"};}}
async function recordInviteResult(userId,result){if(result.sent)await db.query("UPDATE users SET invite_sent_at=now(),updated_at=now() WHERE id=$1",[userId]);return result;}

app.get("/health",async(_req,res,next)=>{try{await db.query("SELECT 1");res.json({ok:true,time:new Date().toISOString(),app:"stork-edit-api"});}catch(e){next(e);}});
app.get("/api/auth/status",async(_req,res,next)=>{try{res.json({ok:true,bootstrapCompleted:Number((await db.query("SELECT count(*) FROM users")).rows[0].count)>0,recoveryAvailable:String(process.env.BOOTSTRAP_TOKEN||"").length>=24});}catch(e){next(e);}});
app.post("/api/bootstrap-admin",loginLimiter,async(req,res,next)=>{try{
  if(Number((await db.query("SELECT count(*) FROM users")).rows[0].count)>0)return res.status(409).json({error:"bootstrap_already_completed"});
  const expected=String(process.env.BOOTSTRAP_TOKEN||""),supplied=String(req.body.bootstrapToken||req.headers["x-bootstrap-token"]||"");if(expected.length<24||supplied!==expected)return res.status(403).json({error:"invalid_bootstrap_token"});
  const email=normalizeEmail(req.body.email),name=String(req.body.name||"").trim();if(!email||!name)return res.status(400).json({error:"email_and_name_required"});
  const user=(await db.query("INSERT INTO users(id,email,name,role,password_hash) VALUES($1,$2,$3,'admin',$4) RETURNING *",[randomId(),email,name,await hashPassword(req.body.password)])).rows[0];res.status(201).json({user:publicUser(user)});
}catch(e){next(e);}});
app.post("/api/recover-admin",loginLimiter,async(req,res,next)=>{try{
  const expected=Buffer.from(String(process.env.BOOTSTRAP_TOKEN||"")),supplied=Buffer.from(String(req.body.bootstrapToken||req.headers["x-bootstrap-token"]||""));
  if(expected.length<24||expected.length!==supplied.length||!crypto.timingSafeEqual(expected,supplied))return res.status(403).json({error:"invalid_recovery_credentials"});
  const email=normalizeEmail(req.body.email),user=(await db.query("SELECT * FROM users WHERE lower(email)=lower($1) AND role='admin'",[email])).rows[0];
  if(!user)return res.status(403).json({error:"invalid_recovery_credentials"});
  const passwordHash=await hashPassword(req.body.newPassword);await db.query("UPDATE users SET password_hash=$1,is_active=true,must_change_password=false,updated_at=now() WHERE id=$2",[passwordHash,user.id]);
  await audit(null,"admin_access_recovered","user",user.id,{email:user.email},req);res.json({ok:true});
}catch(e){next(e);}});
app.post("/api/login",loginLimiter,async(req,res,next)=>{try{const user=(await db.query("SELECT * FROM users WHERE lower(email)=lower($1)",[normalizeEmail(req.body.email)])).rows[0];if(!user||!user.is_active||!await verifyPassword(req.body.password,user.password_hash))return res.status(401).json({error:"invalid_credentials"});await db.query("UPDATE users SET last_login_at=now() WHERE id=$1",[user.id]);await audit(user,"login","user",user.id,{},req);res.json({token:signToken(user),user:publicUser({...user,last_login_at:new Date()})});}catch(e){next(e);}});
app.get("/api/me",authenticateUser,async(req,res)=>res.json({user:publicUser(req.user),individualIds:await assignments(req.user.id),contribution:await contributionForUser(db,req.user)}));
app.get("/api/me/contribution",authenticateUser,async(req,res,next)=>{try{res.json({contribution:await contributionForUser(db,req.user)});}catch(e){next(e);}});
app.post("/api/me/change-password",authenticateUser,writeLimiter,async(req,res,next)=>{try{if(!await verifyPassword(req.body.currentPassword,req.user.password_hash))return res.status(400).json({error:"current_password_incorrect"});await db.query("UPDATE users SET password_hash=$1,must_change_password=false,updated_at=now() WHERE id=$2",[await hashPassword(req.body.newPassword),req.user.id]);await audit(req.user,"password_changed","user",req.user.id,{},req);res.json({ok:true});}catch(e){next(e);}});

app.get("/api/users",authenticateUser,requireRole("admin"),async(_req,res,next)=>{try{const result=await db.query("SELECT * FROM users ORDER BY created_at DESC");res.json({users:await Promise.all(result.rows.map(async(u)=>({...publicUser(u),individualIds:await assignments(u.id),contribution:await contributionForUser(db,u)})))});}catch(e){next(e);}});
app.post("/api/users",authenticateUser,requireRole("admin"),writeLimiter,async(req,res,next)=>{try{
  const email=normalizeEmail(req.body.email),name=String(req.body.name||"").trim(),role=String(req.body.role||"annotator");if(!email||!name||!["admin","coordinator","annotator"].includes(role))return res.status(400).json({error:"invalid_user"});
  const restricted=role==="annotator"&&!!req.body.restrictedContributor,password=req.body.password||temporaryPassword(),hash=await hashPassword(password),id=randomId();const user=await transaction(async(client)=>{const row=(await client.query("INSERT INTO users(id,email,name,role,password_hash,must_change_password,restricted_contributor) VALUES($1,$2,$3,$4,$5,true,$6) RETURNING *",[id,email,name,role,hash,restricted])).rows[0];await setAssignments(client,id,req.body.individualIds);await audit(req.user,"user_created","user",id,{role,restrictedContributor:restricted},req,client);return row;});
  const inviteResult=req.body.sendInvite===false?null:await recordInviteResult(id,await invite(user,password));const refreshed=(await db.query("SELECT * FROM users WHERE id=$1",[id])).rows[0];res.status(201).json({user:{...publicUser(refreshed),individualIds:await assignments(id)},invite:inviteResult});
}catch(e){next(e);}});
app.patch("/api/users/:id",authenticateUser,requireRole("admin"),writeLimiter,async(req,res,next)=>{try{
  const existing=(await db.query("SELECT * FROM users WHERE id=$1",[req.params.id])).rows[0];if(!existing)return res.status(404).json({error:"user_not_found"});const role=req.body.role??existing.role,active=req.body.isActive??existing.is_active;if(!["admin","coordinator","annotator"].includes(role))return res.status(400).json({error:"invalid_role"});if(existing.id===req.user.id&&(role!=="admin"||!active))return res.status(400).json({error:"cannot_remove_own_admin_access"});
  if(existing.role==="admin"&&(role!=="admin"||!active)&&Number((await db.query("SELECT count(*) FROM users WHERE role='admin' AND is_active=true")).rows[0].count)<=1)return res.status(400).json({error:"last_active_admin"});
  const restricted=role==="annotator"?Boolean(req.body.restrictedContributor??existing.restricted_contributor):false,useDefaults=Boolean(req.body.contributionUseDefaults??existing.contribution_use_defaults);
  const user=await transaction(async(client)=>{const row=(await client.query("UPDATE users SET name=$1,role=$2,is_active=$3,restricted_contributor=$4,contribution_use_defaults=$5,updated_at=now() WHERE id=$6 RETURNING *",[String(req.body.name??existing.name).trim(),role,!!active,restricted,useDefaults,existing.id])).rows[0];if(req.body.individualIds!==undefined)await setAssignments(client,existing.id,req.body.individualIds);await audit(req.user,"user_updated","user",existing.id,{role,isActive:!!active,restrictedContributor:restricted,contributionUseDefaults:useDefaults},req,client);return row;});res.json({user:{...publicUser(user),individualIds:await assignments(user.id),contribution:await contributionForUser(db,user)}});
}catch(e){next(e);}});
app.post("/api/users/:id/reset-password",authenticateUser,requireRole("admin"),writeLimiter,async(req,res,next)=>{try{const user=(await db.query("SELECT * FROM users WHERE id=$1",[req.params.id])).rows[0];if(!user)return res.status(404).json({error:"user_not_found"});const password=temporaryPassword();await db.query("UPDATE users SET password_hash=$1,must_change_password=true,updated_at=now() WHERE id=$2",[await hashPassword(password),user.id]);const inviteResult=await recordInviteResult(user.id,await invite(user,password));await audit(req.user,"password_reset","user",user.id,{inviteSent:inviteResult.sent},req);res.json({ok:true,invite:inviteResult});}catch(e){next(e);}});
app.post("/api/users/:id/send-invite",authenticateUser,requireRole("admin"),writeLimiter,async(req,res,next)=>{try{const user=(await db.query("SELECT * FROM users WHERE id=$1",[req.params.id])).rows[0];if(!user)return res.status(404).json({error:"user_not_found"});const password=temporaryPassword();await db.query("UPDATE users SET password_hash=$1,must_change_password=true,is_active=true,updated_at=now() WHERE id=$2",[await hashPassword(password),user.id]);const inviteResult=await recordInviteResult(user.id,await invite(user,password));await audit(req.user,"user_invite_sent","user",user.id,{sent:inviteResult.sent,reason:inviteResult.reason||null},req);res.json({ok:true,invite:inviteResult,user:publicUser((await db.query("SELECT * FROM users WHERE id=$1",[user.id])).rows[0])});}catch(e){next(e);}});

app.get("/api/admin/contribution-settings",authenticateUser,requireRole("admin"),async(_req,res,next)=>{try{res.json({settings:await getContributionSettings(db)});}catch(e){next(e);}});
app.patch("/api/admin/contribution-settings",authenticateUser,requireRole("admin"),writeLimiter,async(req,res,next)=>{try{
  const settings=normalizeContributionSettings(req.body||{});await db.query(`UPDATE contribution_settings SET initial_browsing_allowance=$1,photos_per_completed=$2,best_pictures_threshold=$3,full_access_threshold=$4,acknowledgement_threshold=$5,scientific_threshold=$6,auto_promote_full_access=$7,scientific_message=$8,level_names=$9::jsonb,updated_by=$10,updated_at=now() WHERE id=1`,[settings.initialBrowsingAllowance,settings.photosPerCompleted,settings.bestPicturesThreshold,settings.fullAccessThreshold,settings.acknowledgementThreshold,settings.scientificThreshold,settings.autoPromoteFullAccess,settings.scientificMessage,JSON.stringify(settings.levelNames),req.user.id]);await audit(req.user,"contribution_settings_updated","contribution_settings","1",settings,req);res.json({settings});
}catch(e){if(e.message==="contribution_thresholds_must_increase")return res.status(400).json({error:e.message});next(e);}});
app.put("/api/admin/users/:id/contribution-overrides",authenticateUser,requireRole("admin"),writeLimiter,async(req,res,next)=>{try{
  const user=(await db.query("SELECT * FROM users WHERE id=$1",[req.params.id])).rows[0];if(!user)return res.status(404).json({error:"user_not_found"});const useDefaults=req.body.useDefaults!==false;
  await transaction(async(client)=>{await client.query("UPDATE users SET contribution_use_defaults=$1,updated_at=now() WHERE id=$2",[useDefaults,user.id]);if(useDefaults)await client.query("DELETE FROM user_contribution_overrides WHERE user_id=$1",[user.id]);else{const global=await getContributionSettings(client),settings=normalizeContributionSettings({...global,...req.body});await client.query(`INSERT INTO user_contribution_overrides(user_id,initial_browsing_allowance,photos_per_completed,best_pictures_threshold,full_access_threshold,acknowledgement_threshold,scientific_threshold,auto_promote_full_access,scientific_message,level_names,updated_by,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11,now()) ON CONFLICT(user_id) DO UPDATE SET initial_browsing_allowance=EXCLUDED.initial_browsing_allowance,photos_per_completed=EXCLUDED.photos_per_completed,best_pictures_threshold=EXCLUDED.best_pictures_threshold,full_access_threshold=EXCLUDED.full_access_threshold,acknowledgement_threshold=EXCLUDED.acknowledgement_threshold,scientific_threshold=EXCLUDED.scientific_threshold,auto_promote_full_access=EXCLUDED.auto_promote_full_access,scientific_message=EXCLUDED.scientific_message,level_names=EXCLUDED.level_names,updated_by=EXCLUDED.updated_by,updated_at=now()`,[user.id,settings.initialBrowsingAllowance,settings.photosPerCompleted,settings.bestPicturesThreshold,settings.fullAccessThreshold,settings.acknowledgementThreshold,settings.scientificThreshold,settings.autoPromoteFullAccess,settings.scientificMessage,JSON.stringify(settings.levelNames),req.user.id]);}await audit(req.user,"user_contribution_override_updated","user",user.id,{useDefaults},req,client);});
  const refreshed=(await db.query("SELECT * FROM users WHERE id=$1",[user.id])).rows[0];res.json({ok:true,contribution:await contributionForUser(db,refreshed)});
}catch(e){if(e.message==="contribution_thresholds_must_increase")return res.status(400).json({error:e.message});next(e);}});
app.get("/api/admin/contributors",authenticateUser,requireRole("admin"),async(_req,res,next)=>{try{const users=(await db.query("SELECT * FROM users ORDER BY last_activity_at DESC NULLS LAST,name")).rows;res.json({contributors:await Promise.all(users.map(async(user)=>({user:publicUser(user),individualIds:await assignments(user.id),contribution:await contributionForUser(db,user)})))});}catch(e){next(e);}});

async function customAnnotationOptions(client=db){const rows=(await client.query("SELECT field_key,value FROM annotation_options WHERE status='approved' ORDER BY field_key,value")).rows,out={};for(const row of rows){if(!out[row.field_key])out[row.field_key]=[];out[row.field_key].push(row.value);}return out;}
app.get("/api/schema/annotation",async(_req,res,next)=>{try{res.json(publicAnnotationSchema(await customAnnotationOptions()));}catch(e){next(e);}});
app.post("/api/annotation-options",authenticateUser,writeLimiter,async(req,res,next)=>{try{
  const fieldKey=String(req.body.fieldKey||"").trim(),value=String(req.body.value||"").replaceAll("\0","").trim(),reason=String(req.body.reason||"").replaceAll("\0","").trim();
  if(!EXTENSIBLE_ANNOTATION_FIELDS.includes(fieldKey))return res.status(400).json({error:"field_is_not_extensible"});
  if(!value||value.length>100)return res.status(400).json({error:"invalid_option_value"});
  const approved=["admin","coordinator"].includes(req.user.role);if(!approved&&(!reason||reason.length>500))return res.status(400).json({error:"category_reason_required"});
  const row=(await db.query("INSERT INTO annotation_options(field_key,value,created_by,status,reason,reviewed_by,reviewed_at) VALUES($1,$2,$3,$4,$5,$6,CASE WHEN $4='approved' THEN now() ELSE NULL END) ON CONFLICT(field_key,value) DO UPDATE SET reason=EXCLUDED.reason,status=CASE WHEN annotation_options.status='approved' THEN 'approved' ELSE EXCLUDED.status END RETURNING field_key,value,status,reason",[fieldKey,value,req.user.id,approved?"approved":"pending",reason||null,approved?req.user.id:null])).rows[0];await audit(req.user,approved?"annotation_option_added":"annotation_option_proposed","annotation_option",`${fieldKey}:${value}`,{reason:reason||null},req);res.status(201).json({fieldKey:row.field_key,value:row.value,status:row.status,reason:row.reason});
}catch(e){next(e);}});
app.get("/api/admin/annotation-options",authenticateUser,requireRole("admin","coordinator"),async(req,res,next)=>{try{const status=String(req.query.status||"pending"),params=[],where=[];if(status!=="all"){params.push(status);where.push(`o.status=$${params.length}`);}const rows=(await db.query(`SELECT o.*,creator.name created_by_name,reviewer.name reviewed_by_name FROM annotation_options o LEFT JOIN users creator ON creator.id=o.created_by LEFT JOIN users reviewer ON reviewer.id=o.reviewed_by ${where.length?`WHERE ${where.join(" AND ")}`:""} ORDER BY o.created_at`,params)).rows;res.json({options:rows.map((row)=>({fieldKey:row.field_key,value:row.value,status:row.status,reason:row.reason,replacementValue:row.replacement_value,createdAt:iso(row.created_at),createdBy:row.created_by_name?{id:row.created_by,name:row.created_by_name}:null,reviewedBy:row.reviewed_by_name?{id:row.reviewed_by,name:row.reviewed_by_name}:null}))});}catch(e){next(e);}});
app.patch("/api/admin/annotation-options",authenticateUser,requireRole("admin","coordinator"),writeLimiter,async(req,res,next)=>{try{
  const fieldKey=String(req.body.fieldKey||""),value=String(req.body.value||"").replaceAll("\0","").trim(),action=String(req.body.action||""),replacement=String(req.body.replacementValue||"").replaceAll("\0","").trim();const field=ANNOTATION_FIELDS.find((entry)=>entry.key===fieldKey&&entry.extensible&&entry.table!=="photos");if(!field||!value)return res.status(400).json({error:"invalid_annotation_option"});if(!["approve","reject","rename","merge","delete"].includes(action))return res.status(400).json({error:"invalid_option_action"});if(["rename","merge"].includes(action)&&(!replacement||replacement.length>100))return res.status(400).json({error:"replacement_value_required"});
  await transaction(async(client)=>{if(["rename","merge"].includes(action)){await client.query(`UPDATE photo_annotations SET ${field.db}=$1 WHERE ${field.db}=$2`,[replacement,value]);await client.query("INSERT INTO annotation_options(field_key,value,created_by,status,reviewed_by,reviewed_at) VALUES($1,$2,$3,'approved',$3,now()) ON CONFLICT(field_key,value) DO UPDATE SET status='approved',reviewed_by=$3,reviewed_at=now()",[fieldKey,replacement,req.user.id]);await client.query("DELETE FROM annotation_options WHERE field_key=$1 AND value=$2",[fieldKey,value]);}else if(action==="delete"){await client.query(`UPDATE photo_annotations SET ${field.db}=NULL,status=CASE WHEN status='complete' THEN 'needs_review' ELSE status END,updated_at=now() WHERE ${field.db}=$1`,[value]);await client.query("DELETE FROM annotation_options WHERE field_key=$1 AND value=$2",[fieldKey,value]);}else if(action==="reject"){await client.query(`UPDATE photo_annotations SET ${field.db}=NULL,status=CASE WHEN status='complete' THEN 'needs_review' ELSE status END,updated_at=now() WHERE ${field.db}=$1`,[value]);await client.query("UPDATE annotation_options SET status='rejected',reviewed_by=$1,reviewed_at=now(),replacement_value=$2 WHERE field_key=$3 AND value=$4",[req.user.id,replacement||null,fieldKey,value]);}else await client.query("UPDATE annotation_options SET status='approved',reviewed_by=$1,reviewed_at=now(),replacement_value=NULL WHERE field_key=$2 AND value=$3",[req.user.id,fieldKey,value]);await audit(req.user,`annotation_option_${action}`,"annotation_option",`${fieldKey}:${value}`,{replacement:replacement||null},req,client);});res.json({ok:true});
}catch(e){next(e);}});
app.get("/api/public/individuals",(_req,res)=>res.status(401).json({error:"login_required_for_dataset"}));
app.get("/api/public/individuals/:id/photos",(_req,res)=>res.status(401).json({error:"login_required_for_media"}));
function decimate(points,max){if(points.length<=max)return points;const output=[points[0]],step=(points.length-1)/(max-1);for(let i=1;i<max-1;i++)output.push(points[Math.round(i*step)]);output.push(points.at(-1));return output;}
app.get("/api/public/individuals/:id/route",(_req,res)=>res.status(401).json({error:"login_required_for_dataset"}));
app.get("/api/public/individuals/:id/stopovers",(_req,res)=>res.status(401).json({error:"login_required_for_dataset"}));
app.get("/api/public/photos/:id/image",authenticateMediaUser,authorizeMediaAndServe);

app.get("/api/individuals",authenticateUser,async(req,res,next)=>{try{const result=await db.query("SELECT i.*,count(p.id)::int photo_count,min(p.capture_time) first_photo_at,max(p.capture_time) last_photo_at FROM individuals i LEFT JOIN photos p ON p.individual_id=i.id WHERE i.active=true GROUP BY i.id ORDER BY i.id");res.json({individuals:result.rows.map((row)=>({...row,photoCount:Number(row.photo_count||0),firstPhotoAt:iso(row.first_photo_at),lastPhotoAt:iso(row.last_photo_at)}))});}catch(e){next(e);}});
app.get("/api/individuals/:id/photos",authenticateUser,async(req,res,next)=>{try{if(!await canAccessIndividual(req.user,req.params.id))return res.status(403).json({error:"forbidden"});const rows=(await db.query(`SELECT p.*,${mediaGrantSql("p","$2")} media_granted FROM photos p WHERE p.individual_id=$1 ORDER BY p.capture_time NULLS LAST,p.filename LIMIT $3`,[req.params.id,req.user.id,positiveInt(req.query.limit,5000,10000)])).rows,lazyMedia=req.query.media==="lazy"&&["admin","coordinator"].includes(req.user.role);res.json({photos:rows.map((row)=>photoPublic(row,lazyMedia?null:req.user)),contribution:await contributionForUser(db,req.user)});}catch(e){next(e);}});
app.get("/api/individuals/:id/route",authenticateUser,async(req,res,next)=>{try{if(!await canAccessIndividual(req.user,req.params.id))return res.status(403).json({error:"forbidden"});const rows=(await db.query("SELECT * FROM gps_points WHERE individual_id=$1 ORDER BY observed_at NULLS LAST,sequence_no NULLS LAST",[req.params.id])).rows,raw=rows.map((row)=>({time:iso(row.observed_at),lon:Number(row.longitude),lat:Number(row.latitude),altitudeM:row.altitude_m==null?null:Number(row.altitude_m),type:row.point_type,countN:row.count_n})),max=req.query.detail==="full"?positiveInt(req.query.max,50000,100000):positiveInt(req.query.max,2500,5000);res.json({individualId:req.params.id,total:raw.length,simplified:raw.length>max,points:decimate(raw,max)});}catch(e){next(e);}});
app.get("/api/individuals/:id/stopovers",authenticateUser,async(req,res,next)=>{try{if(!await canAccessIndividual(req.user,req.params.id))return res.status(403).json({error:"forbidden"});const rows=(await db.query("SELECT * FROM stopovers WHERE individual_id=$1 ORDER BY time_start",[req.params.id])).rows;res.json({type:"FeatureCollection",features:rows.map((row)=>({type:"Feature",id:row.id,geometry:row.geometry_geojson,properties:{...row.properties,id:row.individual_id,time_start:iso(row.time_start),time_end:iso(row.time_end)}}))});}catch(e){next(e);}});
app.get("/api/progress",authenticateUser,async(req,res,next)=>{try{const access=accessSql(req.user,"p.individual_id",1),result=await db.query(`SELECT p.individual_id,count(*)::int total,count(*) FILTER(WHERE COALESCE(a.status,'unstarted')='complete')::int complete,count(*) FILTER(WHERE a.status='draft')::int draft,count(*) FILTER(WHERE a.status='needs_review')::int needs_review,count(*) FILTER(WHERE a.status IS NULL OR a.status='unstarted')::int unstarted,count(*) FILTER(WHERE a.status='complete' AND a.quality_selected='no')::int rejected FROM photos p LEFT JOIN photo_annotations a ON a.photo_id=p.id WHERE ${access.sql} GROUP BY p.individual_id ORDER BY p.individual_id`,access.params);res.json({individuals:result.rows.map((r)=>({individualId:r.individual_id,total:r.total,complete:r.complete,draft:r.draft,needsReview:r.needs_review,unstarted:r.unstarted,rejected:r.rejected,percentComplete:r.total?Math.round(r.complete*1000/r.total)/10:0}))});}catch(e){next(e);}});

app.get("/api/manager/contributors",authenticateUser,requireRole("admin","coordinator"),async(_req,res,next)=>{try{const rows=(await db.query(`SELECT u.id,u.name,u.email,u.role,u.is_active,count(*)::int photo_count,max(a.completed_at) last_completed_at FROM photo_annotations a JOIN users u ON u.id=a.completed_by WHERE a.status='complete' GROUP BY u.id,u.name,u.email,u.role,u.is_active ORDER BY lower(u.name),lower(u.email)`)).rows;res.json({contributors:rows.map((row)=>({id:row.id,name:row.name,email:row.email,role:row.role,isActive:row.is_active,photoCount:Number(row.photo_count||0),lastCompletedAt:iso(row.last_completed_at)}))});}catch(error){next(error);}});
app.get("/api/manager/contributors/:id/photos",authenticateUser,requireRole("admin","coordinator"),async(req,res,next)=>{try{const contributor=(await db.query("SELECT * FROM users WHERE id=$1",[req.params.id])).rows[0];if(!contributor)return res.status(404).json({error:"contributor_not_found"});const rows=(await db.query(`SELECT p.id,p.individual_id,p.filename,p.capture_time,p.latitude,p.longitude,p.gps_time,p.location_source,p.altitude_m,p.elevation_m,TRUE media_granted FROM photo_annotations a JOIN photos p ON p.id=a.photo_id WHERE a.completed_by=$1 AND a.status='complete' ORDER BY p.capture_time NULLS LAST,p.individual_id,p.filename`,[contributor.id])).rows;res.json({contributor:publicUser(contributor),total:rows.length,photos:rows.map((row)=>photoPublic(row,null))});}catch(error){next(error);}});

function photoFilters(req,user){const params=[],where=[];const access=accessSql(user,"p.individual_id",1);params.push(...access.params);where.push(access.sql);const add=(sql,value)=>{params.push(value);where.push(sql.replace("?",`$${params.length}`));};if(req.query.individualId)add("p.individual_id=?",req.query.individualId);if(req.query.status)add("COALESCE(a.status,'unstarted')=?",req.query.status);if(req.query.phenoPeriod)add("a.pheno_period=?",req.query.phenoPeriod);if(req.query.periodDay)add("a.period_day=?",req.query.periodDay);if(req.query.residence)add("a.residence=?",req.query.residence);if(req.query.activityClass)add("a.activity_class=?",req.query.activityClass);if(req.query.country)add("p.country=?",req.query.country);if(req.query.dateFrom)add("p.capture_time>=?::date",req.query.dateFrom);if(req.query.dateTo)add("p.capture_time<(?::date+interval '1 day')",req.query.dateTo);if(req.query.search){const base=params.length,value=`%${req.query.search}%`;params.push(value,value,value,value);where.push(`(p.filename ILIKE $${base+1} OR p.individual_id ILIKE $${base+2} OR COALESCE(a.remarks,'') ILIKE $${base+3} OR COALESCE(a.env_desc_en,'') ILIKE $${base+4})`);}return{params,where};}
app.get("/api/photos",authenticateUser,async(req,res,next)=>{try{const page=positiveInt(req.query.page,1,1000000),pageSize=positiveInt(req.query.pageSize,50,500),{params,where}=photoFilters(req,req.user);const count=await db.query(`SELECT count(*)::int count FROM photos p LEFT JOIN photo_annotations a ON a.photo_id=p.id WHERE ${where.join(" AND ")}`,params),queryParams=[...params,req.user.id],userParam=queryParams.length,manager=["admin","coordinator"].includes(req.user.role),isMine=`(a.created_by=$${userParam} OR a.updated_by=$${userParam})`,taskMine=`EXISTS(SELECT 1 FROM annotation_tasks task WHERE task.photo_id=p.id AND task.assigned_to=$${userParam} AND task.status='assigned')`,canEdit=manager?"TRUE":`(${isMine} OR ${taskMine} OR ((a.photo_id IS NULL OR a.status='unstarted') AND EXISTS(SELECT 1 FROM user_individual_access ua WHERE ua.user_id=$${userParam} AND ua.individual_id=p.individual_id)))`,order=manager?"p.individual_id,p.capture_time NULLS LAST,p.filename":`CASE WHEN ${isMine} OR ${taskMine} THEN 0 ELSE 1 END,p.individual_id,p.capture_time NULLS LAST,p.filename`;queryParams.push(pageSize,(page-1)*pageSize);const result=await db.query(`SELECT p.*,p.created_at photo_created_at,p.updated_at photo_updated_at,COALESCE(a.status,'unstarted') status,a.*,a.updated_at annotation_updated_at,u.name updated_by_name,${isMine} is_mine,${canEdit} can_edit,${mediaGrantSql("p",`$${userParam}`)} media_granted FROM photos p LEFT JOIN photo_annotations a ON a.photo_id=p.id LEFT JOIN users u ON u.id=a.updated_by WHERE ${where.join(" AND ")} ORDER BY ${order} LIMIT $${queryParams.length-1} OFFSET $${queryParams.length}`,queryParams);res.json({page,pageSize,total:count.rows[0].count,photos:result.rows.map((row)=>photoJoined(row,req.user)),contribution:await contributionForUser(db,req.user)});}catch(e){next(e);}});
app.get("/api/photos/filter-options",authenticateUser,async(req,res,next)=>{try{const access=accessSql(req.user,"p.individual_id",1),sql=(column)=>db.query(`SELECT DISTINCT ${column} value FROM photos p LEFT JOIN photo_annotations a ON a.photo_id=p.id WHERE ${access.sql} AND ${column} IS NOT NULL AND ${column}<>'' ORDER BY value`,access.params).then((result)=>result.rows.map((row)=>row.value));const [individuals,phenoPeriods,periodDays,residences,activityClasses,countries]=await Promise.all([sql("p.individual_id"),sql("a.pheno_period"),sql("a.period_day"),sql("a.residence"),sql("a.activity_class"),sql("p.country")]);res.json({individuals,phenoPeriods,periodDays,residences,activityClasses,countries});}catch(e){next(e);}});
app.get("/api/photos/:id",authenticateUser,async(req,res,next)=>{try{const row=(await db.query("SELECT p.*,p.created_at photo_created_at,p.updated_at photo_updated_at,COALESCE(a.status,'unstarted') status,a.*,a.updated_at annotation_updated_at,u.name updated_by_name FROM photos p LEFT JOIN photo_annotations a ON a.photo_id=p.id LEFT JOIN users u ON u.id=a.updated_by WHERE p.id=$1",[req.params.id])).rows[0];if(!row)return res.status(404).json({error:"photo_not_found"});if(!await canAccessIndividual(req.user,row.individual_id))return res.status(403).json({error:"forbidden"});const current=row.photo_id?row:null,canEdit=await annotationPermission(req.user,row,current);res.json({photo:photoJoined({...row,can_edit:canEdit,is_mine:!!current&&(current.created_by===req.user.id||current.updated_by===req.user.id)},req.user),contribution:await contributionForUser(db,req.user)});}catch(e){next(e);}});
app.post("/api/photos/:id/access",authenticateUser,writeLimiter,async(req,res,next)=>{try{const purpose=String(req.body.purpose||"browse");if(!["browse","annotation"].includes(purpose))return res.status(400).json({error:"invalid_access_purpose"});const result=await transaction(async(client)=>{let effectivePurpose="browse";if(purpose==="annotation"){const photo=(await client.query("SELECT * FROM photos WHERE id=$1",[req.params.id])).rows[0];if(!photo)return{allowed:false,http:404,error:"photo_not_found"};const current=(await client.query("SELECT * FROM photo_annotations WHERE photo_id=$1",[photo.id])).rows[0]||null;if(!await annotationPermission(req.user,photo,current,client))return{allowed:false,http:403,error:"annotation_read_only"};const taskAssigned=!!(await client.query("SELECT 1 FROM annotation_tasks WHERE assigned_to=$1 AND photo_id=$2 AND status='assigned'",[req.user.id,photo.id])).rows[0],focusActive=!!(await client.query("SELECT 1 FROM restricted_annotation_focus WHERE user_id=$1 AND photo_id=$2",[req.user.id,photo.id])).rows[0],ownCompleted=current?.status==="complete"&&current.completed_by===req.user.id,profile=await contributionForUser(client,req.user);if(profile.restricted&&profile.browseLimitReached&&!taskAssigned&&!focusActive&&!ownCompleted)return{allowed:false,http:403,error:"browsing_limit_reached",profile};effectivePurpose=taskAssigned||focusActive?"annotation":"browse";}return ensurePhotoAccess(client,req.user,req.params.id,{purpose:effectivePurpose});});if(!result.allowed)return res.status(result.http||403).json({error:result.error,contribution:result.profile||null});const photo=(await db.query("SELECT * FROM photos WHERE id=$1",[req.params.id])).rows[0];res.json({ok:true,photo:photoPublic({...photo,media_granted:true},req.user),contribution:result.profile});}catch(e){next(e);}});
app.get("/api/photos/:id/image",authenticateUser,authorizeMediaAndServe);
app.get("/api/photos/:id/download",authenticateUser,async(req,res,next)=>{try{const access=await transaction((client)=>ensurePhotoAccess(client,req.user,req.params.id,{purpose:"browse"}));if(!access.allowed)return res.status(access.http||403).json({error:access.error,contribution:access.profile||null});const photo=(await db.query("SELECT filename,storage_path,media_status FROM photos WHERE id=$1",[req.params.id])).rows[0],file=photo&&safeStorage(photo.storage_path);if(!photo||photo.media_status!=="available"||!file||!fs.existsSync(file))return res.status(404).json({error:"photo_file_missing"});await audit(req.user,"photo_downloaded","photo",req.params.id,{},req);res.download(file,path.basename(photo.filename),(error)=>{if(error&&!res.headersSent)next(error);});}catch(e){next(e);}});

const photoSocial=(row)=>({favorite:!!row.favorite,ownRating:row.own_rating==null?null:Number(row.own_rating),averageRating:row.average_rating==null?null:Math.round(Number(row.average_rating)*10)/10,ratingCount:Number(row.rating_count||0)});
app.get("/api/photos/:id/social",authenticateUser,async(req,res,next)=>{try{const photo=(await db.query("SELECT id,individual_id FROM photos WHERE id=$1",[req.params.id])).rows[0];if(!photo)return res.status(404).json({error:"photo_not_found"});if(!await canAccessIndividual(req.user,photo.individual_id))return res.status(403).json({error:"forbidden"});const row=(await db.query("SELECT EXISTS(SELECT 1 FROM user_photo_favorites WHERE user_id=$1 AND photo_id=$2) favorite,(SELECT rating FROM photo_ratings WHERE user_id=$1 AND photo_id=$2) own_rating,(SELECT avg(rating) FROM photo_ratings WHERE photo_id=$2) average_rating,(SELECT count(*) FROM photo_ratings WHERE photo_id=$2) rating_count",[req.user.id,photo.id])).rows[0];res.json({social:photoSocial(row)});}catch(e){next(e);}});
app.put("/api/photos/:id/favorite",authenticateUser,writeLimiter,async(req,res,next)=>{try{const profile=await contributionForUser(db,req.user);if(!profile.bestPicturesUnlocked)return res.status(403).json({error:"best_pictures_locked",contribution:profile});const photo=(await db.query("SELECT individual_id FROM photos WHERE id=$1",[req.params.id])).rows[0];if(!photo)return res.status(404).json({error:"photo_not_found"});if(!await canAccessIndividual(req.user,photo.individual_id))return res.status(403).json({error:"forbidden"});await db.query("INSERT INTO user_photo_favorites(user_id,photo_id) VALUES($1,$2) ON CONFLICT DO NOTHING",[req.user.id,req.params.id]);await audit(req.user,"favorite_added","photo",req.params.id,{},req);res.json({ok:true,favorite:true});}catch(e){next(e);}});
app.delete("/api/photos/:id/favorite",authenticateUser,writeLimiter,async(req,res,next)=>{try{await db.query("DELETE FROM user_photo_favorites WHERE user_id=$1 AND photo_id=$2",[req.user.id,req.params.id]);await audit(req.user,"favorite_removed","photo",req.params.id,{},req);res.json({ok:true,favorite:false});}catch(e){next(e);}});
app.put("/api/photos/:id/rating",authenticateUser,writeLimiter,async(req,res,next)=>{try{const rating=Number(req.body.rating),photo=(await db.query("SELECT individual_id FROM photos WHERE id=$1",[req.params.id])).rows[0];if(!photo)return res.status(404).json({error:"photo_not_found"});if(!await canAccessIndividual(req.user,photo.individual_id))return res.status(403).json({error:"forbidden"});if(!Number.isInteger(rating)||rating<1||rating>5)return res.status(400).json({error:"invalid_rating"});await db.query("INSERT INTO photo_ratings(user_id,photo_id,rating) VALUES($1,$2,$3) ON CONFLICT(user_id,photo_id) DO UPDATE SET rating=EXCLUDED.rating,updated_at=now()",[req.user.id,req.params.id,rating]);const row=(await db.query("SELECT avg(rating) average_rating,count(*) rating_count FROM photo_ratings WHERE photo_id=$1",[req.params.id])).rows[0];await audit(req.user,"photo_rated","photo",req.params.id,{rating},req);res.json({ok:true,ownRating:rating,averageRating:Math.round(Number(row.average_rating)*10)/10,ratingCount:Number(row.rating_count)});}catch(e){next(e);}});
app.delete("/api/photos/:id/rating",authenticateUser,writeLimiter,async(req,res,next)=>{try{const photo=(await db.query("SELECT individual_id FROM photos WHERE id=$1",[req.params.id])).rows[0];if(!photo)return res.status(404).json({error:"photo_not_found"});if(!await canAccessIndividual(req.user,photo.individual_id))return res.status(403).json({error:"forbidden"});await db.query("DELETE FROM photo_ratings WHERE user_id=$1 AND photo_id=$2",[req.user.id,req.params.id]);const row=(await db.query("SELECT avg(rating) average_rating,count(*) rating_count FROM photo_ratings WHERE photo_id=$1",[req.params.id])).rows[0];await audit(req.user,"photo_rating_removed","photo",req.params.id,{},req);res.json({ok:true,ownRating:null,averageRating:row.average_rating==null?null:Math.round(Number(row.average_rating)*10)/10,ratingCount:Number(row.rating_count)});}catch(e){next(e);}});
app.get("/api/me/photo-collection",authenticateUser,async(req,res,next)=>{try{const profile=await contributionForUser(db,req.user);if(!profile.bestPicturesUnlocked)return res.status(403).json({error:"best_pictures_locked",contribution:profile});const collection=String(req.query.collection||"favorites"),sort=String(req.query.sort||"rating_desc"),access=accessSql(req.user,"p.individual_id",2),params=[req.user.id,...access.params],where=[access.sql];if(collection==="favorites")where.push("f.user_id=$1");else if(collection==="rated")where.push("stats.rating_count>0");else return res.status(400).json({error:"invalid_collection"});const order=sort==="date_desc"?"p.capture_time DESC NULLS LAST":sort==="date_asc"?"p.capture_time NULLS LAST":"stats.average_rating DESC NULLS LAST,p.capture_time DESC NULLS LAST";const rows=(await db.query(`SELECT p.*,f.user_id IS NOT NULL favorite,own.rating own_rating,stats.average_rating,stats.rating_count,${mediaGrantSql("p","$1")} media_granted FROM photos p LEFT JOIN user_photo_favorites f ON f.photo_id=p.id AND f.user_id=$1 LEFT JOIN photo_ratings own ON own.photo_id=p.id AND own.user_id=$1 LEFT JOIN (SELECT photo_id,avg(rating) average_rating,count(*) rating_count FROM photo_ratings GROUP BY photo_id) stats ON stats.photo_id=p.id WHERE ${where.join(" AND ")} ORDER BY ${order} LIMIT 1000`,params)).rows;res.json({photos:rows.map((row)=>({...photoPublic(row,req.user),social:photoSocial(row)})),contribution:profile});}catch(e){next(e);}});

app.get("/api/me/photo-collection/download",authenticateUser,async(req,res,next)=>{try{
  const profile=await contributionForUser(db,req.user);if(!profile.bestPicturesUnlocked)return res.status(403).json({error:"photo_safe_locked",contribution:profile});
  const collection=String(req.query.collection||"rated");let rows,downloadName,auditAction,auditDetails;
  if(collection==="favorites"){
    rows=(await db.query(`SELECT p.* FROM user_photo_favorites f JOIN photos p ON p.id=f.photo_id WHERE f.user_id=$1 AND p.media_status='available' ORDER BY f.created_at DESC LIMIT 1000`,[req.user.id])).rows;
    downloadName="my-photo-safe.zip";auditAction="photo_safe_downloaded";auditDetails={count:rows.length};
  }else if(collection==="rated"){
    const minimumRating=Math.max(1,Math.min(5,Number(req.query.minimumRating)||4));
    rows=(await db.query(`SELECT p.* FROM photos p JOIN (SELECT photo_id,avg(rating) average_rating FROM photo_ratings GROUP BY photo_id HAVING avg(rating)>=$1) rated ON rated.photo_id=p.id WHERE p.media_status='available' ORDER BY rated.average_rating DESC,p.capture_time DESC NULLS LAST LIMIT 1000`,[minimumRating])).rows;
    downloadName=`top-rated-${String(minimumRating).replace(".","-")}.zip`;auditAction="rated_photos_downloaded";auditDetails={minimumRating,count:rows.length};
  }else return res.status(400).json({error:"invalid_collection"});
  if(!rows.length)return res.status(404).json({error:collection==="favorites"?"photo_safe_empty":"no_photos_for_rating_threshold"});
  try{await transaction(async(client)=>{for(const row of rows){const access=await ensurePhotoAccess(client,req.user,row.id,{purpose:"browse"});if(!access.allowed){const error=new Error(access.error);error.http=access.http||403;error.profile=access.profile;throw error;}}});}catch(error){if(error.message==="browsing_limit_reached")return res.status(error.http||403).json({error:error.message,contribution:error.profile||null});throw error;}
  await audit(req.user,auditAction,"photo_collection",null,auditDetails,req);return sendZip(res,rows,[],photoDir,downloadName);
}catch(e){next(e);}});

app.post("/api/photos/:id/review-requests",authenticateUser,writeLimiter,async(req,res,next)=>{try{const fieldKey=normalizeReviewField(req.body.fieldKey),reason=String(req.body.reason||"").replaceAll("\0","").trim(),photo=(await db.query("SELECT individual_id FROM photos WHERE id=$1",[req.params.id])).rows[0];if(!photo)return res.status(404).json({error:"photo_not_found"});if(!await canAccessIndividual(req.user,photo.individual_id))return res.status(403).json({error:"forbidden"});if(!reason||reason.length>1000)return res.status(400).json({error:"review_reason_required"});const id=randomId();await db.query("INSERT INTO annotation_review_requests(id,photo_id,field_key,reason,created_by) VALUES($1,$2,$3,$4,$5)",[id,req.params.id,fieldKey,reason,req.user.id]);await audit(req.user,"review_requested","photo",req.params.id,{fieldKey,reason},req);res.status(201).json({request:{id,photoId:req.params.id,fieldKey,reason,status:"pending"}});}catch(e){next(e);}});
app.get("/api/review-requests",authenticateUser,requireRole("admin","coordinator"),async(req,res,next)=>{try{const status=String(req.query.status||"pending"),params=[],where=[];if(status!=="all"){params.push(status);where.push(`r.status=$${params.length}`);}const access=accessSql(req.user,"p.individual_id",params.length+1);params.push(...access.params);where.push(access.sql);const rows=(await db.query(`SELECT r.*,p.individual_id,p.filename,u.name created_by_name FROM annotation_review_requests r JOIN photos p ON p.id=r.photo_id LEFT JOIN users u ON u.id=r.created_by WHERE ${where.join(" AND ")} ORDER BY r.created_at`,params)).rows;res.json({requests:rows.map((row)=>({id:row.id,photoId:row.photo_id,bird:row.individual_id,filename:row.filename,fieldKey:row.field_key,reason:row.reason,status:row.status,createdAt:iso(row.created_at),createdBy:row.created_by_name?{id:row.created_by,name:row.created_by_name}:null}))});}catch(e){next(e);}});
app.patch("/api/review-requests/:id",authenticateUser,requireRole("admin","coordinator"),writeLimiter,async(req,res,next)=>{try{const status=String(req.body.status||"resolved"),note=String(req.body.resolutionNote||"").replaceAll("\0","").trim(),grantEdit=!!req.body.grantEdit;if(!["resolved","rejected"].includes(status))return res.status(400).json({error:"invalid_review_status"});const existing=(await db.query("SELECT r.*,p.individual_id FROM annotation_review_requests r JOIN photos p ON p.id=r.photo_id WHERE r.id=$1",[req.params.id])).rows[0];if(!existing)return res.status(404).json({error:"review_request_not_found"});if(!await canAccessIndividual(req.user,existing.individual_id))return res.status(403).json({error:"forbidden"});await transaction(async(client)=>{await client.query("UPDATE annotation_review_requests SET status=$1,resolution_note=$2,resolved_by=$3,resolved_at=now() WHERE id=$4",[status,note||null,req.user.id,req.params.id]);if(status==="resolved"&&grantEdit&&existing.created_by)await client.query("INSERT INTO annotation_tasks(id,photo_id,assigned_to,created_by,reason) VALUES($1,$2,$3,$4,$5)",[randomId(),existing.photo_id,existing.created_by,req.user.id,note||"Record released after verification request"]);if(status==="resolved"&&!grantEdit){const annotation=(await client.query("UPDATE photo_annotations SET verified_by=$1,verified_at=CASE WHEN status='complete' THEN now() ELSE verified_at END WHERE photo_id=$2 RETURNING completed_by",[req.user.id,existing.photo_id])).rows[0];if(annotation?.completed_by){const contributor=(await client.query("SELECT * FROM users WHERE id=$1",[annotation.completed_by])).rows[0];if(contributor)await refreshContribution(client,contributor);}}await audit(req.user,"review_request_resolved","review_request",existing.id,{status,note,grantEdit},req,client);});res.json({ok:true,status,grantEdit});}catch(e){next(e);}});

app.get("/api/me/review-requests",authenticateUser,async(req,res,next)=>{try{const rows=(await db.query(`SELECT r.*,p.individual_id,p.filename,resolver.name resolved_by_name FROM annotation_review_requests r JOIN photos p ON p.id=r.photo_id LEFT JOIN users resolver ON resolver.id=r.resolved_by WHERE r.created_by=$1 ORDER BY r.created_at DESC`,[req.user.id])).rows;res.json({requests:rows.map((row)=>({id:row.id,photoId:row.photo_id,bird:row.individual_id,filename:row.filename,fieldKey:row.field_key,reason:row.reason,status:row.status,resolutionNote:row.resolution_note,createdAt:iso(row.created_at),resolvedAt:iso(row.resolved_at),resolvedBy:row.resolved_by_name||null}))});}catch(e){next(e);}});
app.get("/api/me/tasks",authenticateUser,async(req,res,next)=>{try{const rows=(await db.query(`SELECT t.*,p.individual_id,p.filename,creator.name created_by_name FROM annotation_tasks t JOIN photos p ON p.id=t.photo_id LEFT JOIN users creator ON creator.id=t.created_by WHERE t.assigned_to=$1 ORDER BY CASE t.status WHEN 'assigned' THEN 0 ELSE 1 END,t.created_at DESC`,[req.user.id])).rows;res.json({tasks:rows.map((row)=>({id:row.id,photoId:row.photo_id,bird:row.individual_id,filename:row.filename,reason:row.reason,status:row.status,createdAt:iso(row.created_at),createdBy:row.created_by_name||null}))});}catch(e){next(e);}});
app.post("/api/admin/annotation-tasks",authenticateUser,requireRole("admin","coordinator"),writeLimiter,async(req,res,next)=>{try{const assignedTo=String(req.body.assignedTo||""),photoId=String(req.body.photoId||""),reason=String(req.body.reason||"").replaceAll("\0","").trim();if(!assignedTo||!photoId||!reason)return res.status(400).json({error:"task_fields_required"});const target=(await db.query("SELECT id FROM users WHERE id=$1 AND is_active=true",[assignedTo])).rows[0],photo=(await db.query("SELECT id FROM photos WHERE id=$1",[photoId])).rows[0];if(!target||!photo)return res.status(404).json({error:"task_target_not_found"});const id=randomId();await db.query("INSERT INTO annotation_tasks(id,photo_id,assigned_to,created_by,reason) VALUES($1,$2,$3,$4,$5)",[id,photoId,assignedTo,req.user.id,reason]);await audit(req.user,"annotation_task_assigned","photo",photoId,{assignedTo,taskId:id,reason},req);res.status(201).json({task:{id,photoId,assignedTo,reason,status:"assigned"}});}catch(e){next(e);}});

app.patch("/api/photos/:id/annotation",authenticateUser,writeLimiter,async(req,res,next)=>{try{
  const status=String(req.body.status||"draft"),expectedVersion=Number(req.body.expectedVersion??0);if(!["draft","complete","needs_review"].includes(status))return res.status(400).json({error:"invalid_status"});
  const saved=await transaction(async(client)=>{await client.query("SELECT pg_advisory_xact_lock(hashtext($1))",[req.user.id]);const photo=(await client.query("SELECT * FROM photos WHERE id=$1 FOR UPDATE",[req.params.id])).rows[0];if(!photo)return{http:404,body:{error:"photo_not_found"}};if(!await canAccessIndividual(req.user,photo.individual_id,client))return{http:403,body:{error:"forbidden"}};const current=(await client.query("SELECT * FROM photo_annotations WHERE photo_id=$1",[photo.id])).rows[0]||null,currentVersion=Number(current?.version||0);if(!await annotationPermission(req.user,photo,current,client))return{http:403,body:{error:"annotation_read_only"}};if(!Number.isInteger(expectedVersion)||expectedVersion!==currentVersion)return{http:409,body:{error:"version_conflict",currentVersion,current:current?fromDbAnnotation({...current,elevation_m:photo.elevation_m}):null}};if(status==="draft"){const active=(await client.query("SELECT a.photo_id,p.individual_id,p.filename FROM photo_annotations a JOIN photos p ON p.id=a.photo_id WHERE a.updated_by=$1 AND a.status='draft' AND a.photo_id<>$2 ORDER BY a.updated_at DESC LIMIT 1",[req.user.id,photo.id])).rows[0];if(active)return{http:409,body:{error:"active_draft_exists",activeDraft:{photoId:active.photo_id,bird:active.individual_id,filename:active.filename}}};}
    const values=normalizeAnnotationInput(req.body.values||{},photo),errors=validateAnnotation(values,status);if(errors.length)return{http:422,body:{error:"validation_failed",fields:errors}};if(values.Elevation_m!==photo.elevation_m)await client.query("UPDATE photos SET elevation_m=$1,updated_at=now() WHERE id=$2",[values.Elevation_m,photo.id]);
    const dbValues=toDbAnnotation(values),columns=ANNOTATION_DB_COLUMNS,newVersion=currentVersion+1,columnValues=columns.map((c)=>dbValues[c]);let annotation;
    if(!current){const names=["photo_id","status","version",...columns,"created_by","updated_by","completed_at","completed_by"],params=[photo.id,status,newVersion,...columnValues,req.user.id,req.user.id,status==="complete"?new Date():null,status==="complete"?req.user.id:null];annotation=(await client.query(`INSERT INTO photo_annotations(${names.join(",")}) VALUES(${params.map((_,i)=>`$${i+1}`).join(",")}) RETURNING *`,params)).rows[0];}
    else{const completedBy=status==="complete"?(current.status==="complete"?current.completed_by||req.user.id:req.user.id):current.completed_by,params=[photo.id,status,newVersion,...columnValues,req.user.id,status==="complete"?new Date():null,completedBy],assignments=columns.map((c,i)=>`${c}=$${i+4}`);annotation=(await client.query(`UPDATE photo_annotations SET status=$2,version=$3,${assignments.join(",")},updated_by=$${params.length-2},completed_at=$${params.length-1},completed_by=$${params.length},verified_by=CASE WHEN $2='complete' THEN verified_by ELSE NULL END,verified_at=CASE WHEN $2='complete' THEN verified_at ELSE NULL END,updated_at=now() WHERE photo_id=$1 RETURNING *`,params)).rows[0];}
    const startsNewBrowseCycle=req.user.role==="annotator"&&req.user.restricted_contributor&&status==="complete"&&current?.status!=="complete"&&annotation.completed_by===req.user.id;
    if(status==="complete"){
      await client.query("UPDATE annotation_tasks SET status='completed',completed_at=now() WHERE photo_id=$1 AND assigned_to=$2 AND status='assigned'",[photo.id,req.user.id]);
      if(startsNewBrowseCycle){
        await advanceBrowseCycle(client,req.user.id,photo.id);
        await client.query("DELETE FROM restricted_annotation_focus WHERE user_id=$1",[req.user.id]);
      }else await client.query("DELETE FROM restricted_annotation_focus WHERE user_id=$1 AND photo_id=$2",[req.user.id,photo.id]);
    }
    const snapshot={...fromDbAnnotation({...annotation,elevation_m:values.Elevation_m}),status,version:newVersion};await client.query("INSERT INTO annotation_history(photo_id,version,status,changed_by,snapshot) VALUES($1,$2,$3,$4,$5::jsonb)",[photo.id,newVersion,status,req.user.id,JSON.stringify(snapshot)]);await audit(req.user,"annotation_saved","photo",photo.id,{status,version:newVersion,browseCycleAdvanced:startsNewBrowseCycle},req,client);const affected=new Set([req.user.id,current?.completed_by,annotation.completed_by].filter(Boolean));for(const userId of affected){const target=(await client.query("SELECT * FROM users WHERE id=$1",[userId])).rows[0];if(target)await refreshContribution(client,target);}return{http:200,body:{ok:true,status,version:newVersion,values:snapshot,contribution:await contributionForUser(client,req.user)}};
  });res.status(saved.http).json(saved.body);
}catch(e){next(e);}});

app.get("/api/next-unfinished",authenticateUser,async(req,res,next)=>{try{
  const result=await transaction(async(client)=>{
    const profile=await contributionForUser(client,req.user),params=[],where=["COALESCE(a.status,'unstarted') <> 'complete'","p.latitude IS NOT NULL","p.longitude IS NOT NULL"];
    if(req.user.role==="annotator"){params.push(req.user.id);where.push(`((a.created_by=$1 OR a.updated_by=$1) OR EXISTS(SELECT 1 FROM annotation_tasks t WHERE t.photo_id=p.id AND t.assigned_to=$1 AND t.status='assigned') OR ((a.photo_id IS NULL OR a.status='unstarted') AND EXISTS(SELECT 1 FROM user_individual_access ua WHERE ua.user_id=$1 AND ua.individual_id=p.individual_id)))`);}
    if(req.query.individualId){params.push(req.query.individualId);where.push(`p.individual_id=$${params.length}`);}
    if(req.query.after){params.push(req.query.after);where.push(`(p.capture_time,p.filename) > (SELECT capture_time,filename FROM photos WHERE id=$${params.length})`);}
    if(profile.restricted&&profile.browseLimitReached){
      await client.query("SELECT pg_advisory_xact_lock(hashtext($1))",[`annotation-focus:${req.user.id}`]);
      await client.query(`DELETE FROM restricted_annotation_focus f WHERE f.user_id=$1 AND EXISTS(SELECT 1 FROM photos p LEFT JOIN photo_annotations a ON a.photo_id=p.id WHERE p.id=f.photo_id AND (COALESCE(a.status,'unstarted')='complete' OR p.latitude IS NULL OR p.longitude IS NULL))`,[req.user.id]);
      if(req.user.role==="annotator")await client.query(`DELETE FROM restricted_annotation_focus f WHERE f.user_id=$1 AND NOT EXISTS(SELECT 1 FROM photos p LEFT JOIN photo_annotations a ON a.photo_id=p.id WHERE p.id=f.photo_id AND COALESCE(a.status,'unstarted')<>'complete' AND p.latitude IS NOT NULL AND p.longitude IS NOT NULL AND ((a.created_by=$1 OR a.updated_by=$1) OR EXISTS(SELECT 1 FROM annotation_tasks t WHERE t.photo_id=p.id AND t.assigned_to=$1 AND t.status='assigned') OR ((a.photo_id IS NULL OR a.status='unstarted') AND EXISTS(SELECT 1 FROM user_individual_access ua WHERE ua.user_id=$1 AND ua.individual_id=p.individual_id))))`,[req.user.id]);
      let focused=(await client.query(`SELECT p.* FROM restricted_annotation_focus f JOIN photos p ON p.id=f.photo_id LEFT JOIN photo_annotations a ON a.photo_id=p.id WHERE f.user_id=$1 AND COALESCE(a.status,'unstarted')<>'complete' AND p.latitude IS NOT NULL AND p.longitude IS NOT NULL ORDER BY f.granted_at,p.capture_time NULLS LAST,p.filename LIMIT 5`,[req.user.id])).rows;
      let targetBird=focused[0]?.individual_id||null;
      if(!targetBird){const first=(await client.query(`SELECT p.* FROM photos p LEFT JOIN photo_annotations a ON a.photo_id=p.id WHERE ${where.join(" AND ")} ORDER BY p.capture_time NULLS LAST,p.filename LIMIT 1`,params)).rows[0];targetBird=first?.individual_id||null;}
      if(targetBird&&focused.length<5){const candidateParams=[...params,targetBird,req.user.id,5-focused.length],birdParam=candidateParams.length-2,userParam=candidateParams.length-1,limitParam=candidateParams.length,candidates=(await client.query(`SELECT p.* FROM photos p LEFT JOIN photo_annotations a ON a.photo_id=p.id WHERE ${where.join(" AND ")} AND p.individual_id=$${birdParam} AND NOT EXISTS(SELECT 1 FROM restricted_annotation_focus f WHERE f.user_id=$${userParam} AND f.photo_id=p.id) ORDER BY p.capture_time NULLS LAST,p.filename LIMIT $${limitParam}`,candidateParams)).rows;for(const row of candidates)await client.query("INSERT INTO restricted_annotation_focus(user_id,photo_id,granted_at) VALUES($1,$2,now()) ON CONFLICT(user_id,photo_id) DO NOTHING",[req.user.id,row.id]);}
      focused=(await client.query(`SELECT p.* FROM restricted_annotation_focus f JOIN photos p ON p.id=f.photo_id LEFT JOIN photo_annotations a ON a.photo_id=p.id WHERE f.user_id=$1 AND COALESCE(a.status,'unstarted')<>'complete' AND p.latitude IS NOT NULL AND p.longitude IS NOT NULL ORDER BY f.granted_at,p.capture_time NULLS LAST,p.filename LIMIT 5`,[req.user.id])).rows;
      for(const row of focused)await ensurePhotoAccess(client,req.user,row.id,{purpose:"annotation"});
      return{photos:focused,profile};
    }
    const row=(await client.query(`SELECT p.* FROM photos p LEFT JOIN photo_annotations a ON a.photo_id=p.id WHERE ${where.join(" AND ")} ORDER BY p.capture_time NULLS LAST,p.filename LIMIT 1`,params)).rows[0]||null;
    if(row)await ensurePhotoAccess(client,req.user,row.id,{purpose:"browse"});
    return{photos:row?[row]:[],profile};
  });
  const photos=result.photos.map((photo)=>photoPublic({...photo,media_granted:true},req.user));res.json({photo:photos[0]||null,photos,contribution:result.profile});
}catch(e){next(e);}});
app.get("/api/export",authenticateUser,requireRole("admin","coordinator"),async(req,res,next)=>{try{const source=await queryExportRows(db,req.user,{individualId:req.query.individualId||null,status:req.query.status||null,search:req.query.search||null}),rows=source.map((r)=>rowToExport(r,publicApiUrl)),format=String(req.query.format||"xlsx").toLowerCase();await audit(req.user,"data_exported","export",null,{format,count:rows.length},req);if(format==="csv")return sendCsv(res,rows);if(format==="json")return res.attachment("stork-photo-data.json").json(rows);if(format==="geojson")return sendGeoJson(res,rows);if(format==="kml")return sendKml(res,rows);if(format==="zip")return sendZip(res,source,rows,photoDir);return sendXlsx(res,rows);}catch(e){next(e);}});

const publicImportBatch=(row)=>({id:row.id,sourceName:row.source_name,status:row.status,summary:row.summary||{},createdAt:iso(row.created_at),finishedAt:iso(row.finished_at),createdBy:row.created_by_name?{id:row.created_by,name:row.created_by_name}:null});
const safeImportStage=(value)=>{if(!value)return null;const absolute=path.resolve(value),relative=path.relative(importStageDir,absolute);return relative&&!relative.startsWith("..")&&!path.isAbsolute(relative)?absolute:null;};
async function processImportBatch(row,user,requestIp){
  try{const stage=safeImportStage(row.staging_path);if(!stage||!fs.existsSync(stage))throw new Error("import_staging_missing");const reportPath=path.join(stage,"report-applied.json"),report=await runStagedImport({batchId:row.id,createdBy:user.id,manifest:row.input_manifest,reportPath,apply:true,replaceAnnotations:false});await audit(user,"import_completed","import_batch",row.id,report.summary,{ip:requestIp});await removeStagedImport(stage);await db.query("UPDATE import_batches SET staging_path=NULL,input_manifest=$1::jsonb WHERE id=$2",[JSON.stringify({sourceName:row.source_name}),row.id]);}
  catch(error){console.error(`Import ${row.id} failed.`,error);await db.query("UPDATE import_batches SET status='failed',summary=summary||$1::jsonb,finished_at=now() WHERE id=$2",[JSON.stringify({error:String(error.message||"import_failed")}),row.id]).catch(()=>{});}
}

app.get("/api/admin/imports",authenticateUser,requireRole("admin"),async(req,res,next)=>{try{
  const result=await db.query("SELECT b.*,u.name created_by_name FROM import_batches b LEFT JOIN users u ON u.id=b.created_by ORDER BY b.created_at DESC LIMIT $1",[positiveInt(req.query.limit,30,100)]);
  res.json({imports:result.rows.map(publicImportBatch)});
}catch(e){next(e);}});
app.get("/api/admin/imports/:id",authenticateUser,requireRole("admin"),async(req,res,next)=>{try{
  const row=(await db.query("SELECT b.*,u.name created_by_name FROM import_batches b LEFT JOIN users u ON u.id=b.created_by WHERE b.id=$1",[req.params.id])).rows[0];if(!row)return res.status(404).json({error:"import_not_found"});
  const issues=(await db.query("SELECT issue_type,source_row,source_key,details,created_at FROM import_issues WHERE batch_id=$1 ORDER BY id LIMIT 500",[row.id])).rows;
  res.json({import:publicImportBatch(row),issues});
}catch(e){next(e);}});
app.post("/api/admin/imports/columns",authenticateUser,requireRole("admin"),writeLimiter,uploadTableInspect,async(req,res,next)=>{try{
  if(!req.file)return res.status(400).json({error:"tabular_file_required"});
  const result=await inspectTabularHeaders(req.file.path,req.file.originalname);res.json(result);
}catch(e){next(e);}finally{if(req.file?.path)await fsp.unlink(req.file.path).catch(()=>{});}});
app.post("/api/admin/imports/preview",authenticateUser,requireRole("admin"),writeLimiter,uploadImport,async(req,res,next)=>{const batchId=randomId();let staged=null;try{
  const hasFiles=Object.values(req.files||{}).some((group)=>group?.length);if(!hasFiles)return res.status(400).json({error:"import_files_required"});
  staged=await stageBrowserImport({batchId,files:req.files,body:req.body,stageRoot:importStageDir,maxEntries:positiveInt(process.env.MAX_IMPORT_ENTRIES,10000,25000)});
  const reportPath=path.join(staged.stage,"report-preview.json"),report=await runStagedImport({batchId,createdBy:req.user.id,manifest:staged.manifest,reportPath});
  await db.query("INSERT INTO import_batches(id,source_name,source_sha256,status,summary,input_manifest,staging_path,created_by) VALUES($1,$2,$3,'previewed',$4::jsonb,$5::jsonb,$6,$7)",[batchId,staged.manifest.sourceName,report.inputs?.workbookSha256||null,JSON.stringify(report.summary),JSON.stringify(staged.manifest),staged.stage,req.user.id]);
  await audit(req.user,"import_previewed","import_batch",batchId,report.summary,req);res.status(201).json({import:{id:batchId,sourceName:staged.manifest.sourceName,status:"previewed",summary:report.summary,createdAt:new Date().toISOString(),createdBy:{id:req.user.id,name:req.user.name}},issues:report.issues.slice(0,500),issueCount:report.issues.length});
}catch(e){
  if(staged){await db.query("INSERT INTO import_batches(id,source_name,status,summary,staging_path,created_by,finished_at) VALUES($1,$2,'failed',$3::jsonb,$4,$5,now()) ON CONFLICT(id) DO UPDATE SET status='failed',summary=EXCLUDED.summary,finished_at=now()",[batchId,staged.manifest?.sourceName||"browser import",JSON.stringify({error:String(e.message||"preview_failed")}),staged.stage,req.user.id]).catch(()=>{});await removeStagedImport(staged.stage);}
  next(e);
}});
app.post("/api/admin/imports/:id/apply",authenticateUser,requireRole("admin"),writeLimiter,async(req,res,next)=>{try{
  const row=(await db.query("UPDATE import_batches SET status='started' WHERE id=$1 AND status='previewed' RETURNING *",[req.params.id])).rows[0];if(!row)return res.status(409).json({error:"import_not_ready"});
  res.status(202).json({import:{id:row.id,sourceName:row.source_name,status:"started",summary:row.summary}});void processImportBatch(row,req.user,req.ip);
}catch(e){next(e);}});
app.delete("/api/admin/imports/:id",authenticateUser,requireRole("admin"),writeLimiter,async(req,res,next)=>{try{
  const row=(await db.query("SELECT * FROM import_batches WHERE id=$1",[req.params.id])).rows[0];if(!row)return res.status(404).json({error:"import_not_found"});if(!["previewed","failed"].includes(row.status))return res.status(409).json({error:"import_cannot_be_cancelled"});
  const stage=safeImportStage(row.staging_path);if(stage)await removeStagedImport(stage);await db.query("UPDATE import_batches SET status='cancelled',staging_path=NULL,input_manifest='{}'::jsonb,finished_at=now() WHERE id=$1",[row.id]);await audit(req.user,"import_cancelled","import_batch",row.id,{},req);res.json({ok:true});
}catch(e){next(e);}});

app.post("/api/admin/photos",authenticateUser,requireRole("admin"),writeLimiter,uploadPhoto.single("photo"),async(req,res,next)=>{
  let target=null,removeTargetOnError=true;
  try{
    if(!req.file)return res.status(400).json({error:"photo_required"});
    const individualId=String(req.body.individualId||"").trim();
    if(!/^[A-Za-z0-9._-]+$/.test(individualId)||!(await db.query("SELECT 1 FROM individuals WHERE id=$1",[individualId])).rows[0]){await fsp.unlink(req.file.path).catch(()=>{});return res.status(400).json({error:"individual_not_found"});}
    const filename=String(req.body.filename||req.file.originalname),captureTime=req.body.captureTime||parsePhotoFilename(filename).captureTime||null,bytes=await fsp.readFile(req.file.path),sha256=crypto.createHash("sha256").update(bytes).digest("hex"),existing=(await db.query("SELECT * FROM photos WHERE individual_id=$1 AND filename=$2",[individualId,filename])).rows[0];
    let exif={hasGps:false,latitude:null,longitude:null,altitudeM:null,gpsTime:null};try{exif=await readPhotoExifGps(req.file.path);}catch(error){console.warn(`EXIF read failed for upload ${req.file.originalname}.`,error.message);}
    const location=await resolveUploadedPhotoLocation(individualId,captureTime,exif),upgradesGeotag=!!existing&&shouldUpgradePhotoMedia(existing.location_source,location.locationSource);
    if(existing&&!upgradesGeotag){
      if(existing.location_source!=="exif"&&location.locationSource==="track")await db.query("UPDATE photos SET latitude=$1,longitude=$2,gps_time=$3,altitude_m=COALESCE(altitude_m,$4),location_source='track',updated_at=now() WHERE id=$5",[location.latitude,location.longitude,location.gpsTime,location.altitudeM,existing.id]);
      await fsp.unlink(req.file.path).catch(()=>{});const current=(await db.query("SELECT * FROM photos WHERE id=$1",[existing.id])).rows[0];
      await audit(req.user,"photo_duplicate_skipped","photo",existing.id,{individualId,filename,locationSource:current.location_source},req);return res.status(200).json({photo:photoPublic(current,req.user),duplicate:true,replaced:false});
    }
    const ext={"image/jpeg":".jpg","image/png":".png","image/webp":".webp"}[req.file.mimetype]||".jpg",dir=path.join(photoDir,individualId);await fsp.mkdir(dir,{recursive:true});
    target=existing?.storage_path?safeStorage(existing.storage_path):null;if(target)removeTargetOnError=false;else target=path.join(dir,`${randomId()}${ext}`);await fsp.copyFile(req.file.path,target);await fsp.unlink(req.file.path).catch(()=>{});
    const id=existing?.id||randomId(),result=existing?await db.query("UPDATE photos SET capture_time=COALESCE(capture_time,$1),storage_path=$2,original_path=$3,mime_type=$4,size_bytes=$5,sha256=$6,media_status='available',latitude=$7,longitude=$8,gps_time=$9,location_source=$10,exif_checked_at=now(),altitude_m=COALESCE($11,altitude_m),updated_at=now() WHERE id=$12 RETURNING *",[captureTime,path.relative(photoDir,target),req.file.originalname,req.file.mimetype,req.file.size,sha256,location.latitude,location.longitude,location.gpsTime,location.locationSource,location.altitudeM,id]):await db.query("INSERT INTO photos(id,individual_id,filename,capture_time,storage_path,original_path,mime_type,size_bytes,sha256,latitude,longitude,gps_time,location_source,exif_checked_at,altitude_m) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,now(),$14) RETURNING *",[id,individualId,filename,captureTime,path.relative(photoDir,target),req.file.originalname,req.file.mimetype,req.file.size,sha256,location.latitude,location.longitude,location.gpsTime,location.locationSource,location.altitudeM]);
    await audit(req.user,existing?"photo_replaced_with_geotag":"photo_uploaded","photo",id,{individualId,filename:result.rows[0].filename,locationSource:result.rows[0].location_source},req);res.status(existing?200:201).json({photo:photoPublic(result.rows[0],req.user),duplicate:false,replaced:!!existing});
  }catch(e){if(target&&removeTargetOnError)await fsp.unlink(target).catch(()=>{});if(req.file?.path)await fsp.unlink(req.file.path).catch(()=>{});next(e);}
});

app.delete("/api/admin/photos/:id",authenticateUser,requireRole("admin"),writeLimiter,async(req,res,next)=>{try{
  const photo=(await db.query("SELECT id,individual_id,filename,storage_path FROM photos WHERE id=$1",[req.params.id])).rows[0];if(!photo)return res.status(404).json({error:"photo_not_found"});
  await transaction(async(client)=>{await client.query("DELETE FROM photos WHERE id=$1",[photo.id]);await audit(req.user,"photo_deleted","photo",photo.id,{individualId:photo.individual_id,filename:photo.filename,mapDataPreserved:true},req,client);});
  const stored=safeStorage(photo.storage_path);if(stored)await fsp.unlink(stored).catch((error)=>{if(error.code!=="ENOENT")console.warn(`Could not remove photo file ${photo.id}.`,error.message);});await fsp.unlink(path.join(previewDir,`${photo.id}.webp`)).catch(()=>{});
  res.json({ok:true,deletedPhotoId:photo.id,annotationsDeleted:true,gpsAndStopoversPreserved:true});
}catch(e){next(e);}});

app.use((error,_req,res,_next)=>{console.error(error);if(error.code==="23505")return res.status(409).json({error:"duplicate_value",detail:error.detail});if(error.code==="LIMIT_FILE_SIZE")return res.status(413).json({error:"file_too_large"});if(error.code==="LIMIT_FILE_COUNT")return res.status(413).json({error:"too_many_files"});if(["invalid_upload_path","archive_has_too_many_files"].includes(error.message))return res.status(400).json({error:error.message});if(String(error.message||"").includes("CORS"))return res.status(403).json({error:"cors_forbidden"});res.status(500).json({error:"server_error"});});
const server=app.listen(port,()=>console.log(`Stork Edit API listening on port ${port}`));
async function shutdown(signal){console.log(`${signal}: closing server`);server.close(async()=>{await db.end();process.exit(0);});}
process.on("SIGTERM",()=>shutdown("SIGTERM"));process.on("SIGINT",()=>shutdown("SIGINT"));
