import ExcelJS from "exceljs";

export const SURVEY_LONG_HEADERS=["survey_id","response_id","photo_id","rating","sex","year_of_birth","education","nationality","country_of_residence","settlement_size","photography_experience","wildlife_photography_experience","birdwatching_experience","nature_observation_frequency","white_stork_knowledge","started_at","completed_at","duration","quality_flags","included"];
export const SURVEY_SUMMARY_HEADERS=["survey_id","survey_name","status","started_responses","completed_responses","incomplete_responses","completion_rate_percent","average_duration_seconds","median_duration_seconds","average_rating","included_ratings","created_at","expires_at"];
const value=(row,key)=>key in row?row[key]:row.demographics?.[key]??"";
const csv=(input)=>{const text=Array.isArray(input)?input.join("|"):input==null?"":String(input);return /[",\r\n]/.test(text)?`"${text.replaceAll('"','""')}"`:text;};
export const surveyLongRows=(rows)=>rows.map((row)=>Object.fromEntries(SURVEY_LONG_HEADERS.map((key)=>[key,value(row,key)])));
export function sendSurveyCsv(res,rows,filename="survey-long-format.csv"){res.type("text/csv; charset=utf-8").attachment(filename);res.write("\uFEFF"+SURVEY_LONG_HEADERS.join(",")+"\r\n");for(const row of surveyLongRows(rows))res.write(SURVEY_LONG_HEADERS.map((key)=>csv(row[key])).join(",")+"\r\n");res.end();}
export async function sendSurveyXlsx(res,rows,filename="survey-long-format.xlsx"){const workbook=new ExcelJS.Workbook(),sheet=workbook.addWorksheet("survey ratings",{views:[{state:"frozen",ySplit:1}]});sheet.columns=SURVEY_LONG_HEADERS.map((header)=>({header,key:header,width:Math.min(34,Math.max(12,header.length+2))}));for(const row of surveyLongRows(rows))sheet.addRow(row);sheet.getRow(1).font={bold:true,color:{argb:"FFFFFFFF"}};sheet.getRow(1).fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF173A4B"}};sheet.autoFilter={from:"A1",to:`${sheet.getColumn(SURVEY_LONG_HEADERS.length).letter}1`};res.type("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet").attachment(filename);await workbook.xlsx.write(res);res.end();}

const summaryRows=(rows)=>rows.map((row)=>Object.fromEntries(SURVEY_SUMMARY_HEADERS.map((key)=>[key,row[key]??""])));
export function sendSurveySummaryCsv(res,rows,filename="survey-summary.csv"){res.type("text/csv; charset=utf-8").attachment(filename);res.write("\uFEFF"+SURVEY_SUMMARY_HEADERS.join(",")+"\r\n");for(const row of summaryRows(rows))res.write(SURVEY_SUMMARY_HEADERS.map((key)=>csv(row[key])).join(",")+"\r\n");res.end();}
export async function sendSurveySummaryXlsx(res,rows,filename="survey-summary.xlsx"){const workbook=new ExcelJS.Workbook(),sheet=workbook.addWorksheet("survey summary",{views:[{state:"frozen",ySplit:1}]});sheet.columns=SURVEY_SUMMARY_HEADERS.map((header)=>({header,key:header,width:Math.min(34,Math.max(12,header.length+2))}));for(const row of summaryRows(rows))sheet.addRow(row);sheet.getRow(1).font={bold:true,color:{argb:"FFFFFFFF"}};sheet.getRow(1).fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF173A4B"}};sheet.autoFilter={from:"A1",to:`${sheet.getColumn(SURVEY_SUMMARY_HEADERS.length).letter}1`};res.type("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet").attachment(filename);await workbook.xlsx.write(res);res.end();}
